I~'ord Length: (Agirre et al., 1998) note that their predictions for the correct spelling of misspelled words are more accurate for words longer than four characters, and much less accurate for shorter words.
P98-1003
(Elmi and Evens, 1998).
P98-1059
For example, Min (1996) found that while only 0.6% of words in 300 e-mails were misspelled, this meant that 12% of the sentences contained an error (discussed in (Min and Wilson, 1998)).
P98-2142
Corpus frequency: (Vosse, 1992) differentiates between misspellings and neologisms (new words) in terms of their frequency.
A92-1015
(van Halteren et al., 1998) who found that combining the results of several part of speech taggers increased performance).
P98-1081
(Granger, 1983) uses expectations generated by scripts to anMyze unknown words.
J83-3005
(Elworthy, 1998).
W98-1111
Research that is more similar in goal to that outlined in this paper is Vosse (Vosse, 1992).
A92-1015
Vv'e use an in-house statistical tagger (based on (Church, 1988)) to tag the text in which the unknown word occurs.
A88-1019
