We extended the existing scoring scheme of (Mellish et al., 1998) to account for features for local coherence, embedding and semantic parataxis.
W98-1411
3. The embedded part does not lie between text spans connected by semantic parataxis or hypotaxis (Cheng, 1998).
P98-2242
In addition to the semantic relations and the Joint relation 1 used in (Mellish et al., 1998), we assume a Conjunct or Disjunct relation between two facts with at least two identical components, so that semantic parataxis can be treated as a combining operation on two subtrees connected by the relation.
W98-1411
center transitions as defined in Centering Theory (Grosz et al., 1995)).
J95-2003
ac. uk Abstract In natural language generation, different generation tasks often interact with each other in a complex way, which is hard to capture in the pipeline architecture described by Reiter (Reiter, 1994).
W94-0319
in a GA Text Planner To experiment with the interaction between maintaining local coherence and embedding, we adopt the text planner based on a Genetic Algorithm (GA) as described in (Mellish et al., 1998).
W98-1411
Here is the preferences concerning the use of relations, where "A>B" means that A is preferred over B: 1In (Mellish et al., 1998), a Joint relation is used to connect every two text spans that do not have a normal semantic relation in between.
W98-1411
In automatic natural language generation (NLG), various versions of the pipeline architecture specified by Reiter and Dale ((Reiter, 1994) and (Reiter and Dale, 1997)) are usually adopted.
W94-0319
The algorithm of (Mellish et al., 1998) is basically a repeated two step process first sequences of facts are generated by applying GA operators (crossover and mutation) and then the RS trees built from these sequences are evaluated.
W98-1411
