Some researchers (Haas, 1989; Torenvliet and Trautwein, 1995) conjecture that some of the OLP variants are undecidable (it is undecidable whether a grammar satis es the constraint), although none of them gives any proof of it.
J89-4001
A uni cation grammar is depth-bounded iff for every a4a3a68a31a187 there is a a186a188a68a31a187 such that every parse tree for a sentential form of a4 symbols has depth less than a186 . According to Haas (1989), a depth-bounded grammar cannot build an unbounded amount of tree structure from a bounded number of symbols . Therefore, for each sentential form of lengtha95 there exist a nite number of partial derivation trees, guaranteeing parsing termination.
J89-4001
3 Off-line-parsability constraints It is well known that uni cation based grammar formalisms are Turing-equivalent in their generative capacity (Pereira and Warren, 1983; Johnson, 1988, 87-93); determining whether a given string a1 is generated by a given grammar a0 is equivalent to deciding whether a Turing machine a152 halts on an empty input, which is known to be undecidable.
P83-1021
There exist several variants of OLP in the literature (Pereira and Warren, 1983; Johnson, 1988; Haas, 1989; Torenvliet and Trautwein, 1995; Shieber, 1992; Wintner and Francez, 1999; Kuhn, 1999).
J89-4001 P83-1021
One of the rst de nitions was suggested by Pereira and Warren (1983).
P83-1021
Some of the constraints (Pereira and Warren, 1983; Kaplan and Bresnan, 1982; Johnson, 1988; Kuhn, 1999) apply only to skeletal grammars since they use the term category which is not well de ned for general unication grammars.
P83-1021
Others (Haas, 1989; Shieber, 1992; Torenvliet and Trautwein, 1995; Wintner and Francez, 1999) are applicable to both skeletal and general uni cation grammars.
J89-4001
The rst constraint was suggested by Haas (1989).
J89-4001
