9We convert the parse to a dependency format that makes some of our features simpler using a method similar to the one described in Xia and Palmer (2001).
H01-1014
Wiebe (1994), studies methods to track the change of “point of view” in narrative text (fiction).
J94-2004
See (Eisner, 1996, page 17) and (Chinchor et al., 1993, pages 430-433) for descriptions of this method.
J93-3001
The corpus (see Section 4) is distributed with annotations for sentence breaks, tokenization, and part of speech information automatically generated by the GATE toolkit (Cunningham et al., 2002).8 For parsing we use the Collins (1999) parser.9 For partial parses, we employ CASS (Abney, 1997).
P02-1022
Automatic identification of sources has also been addressed indirectly by Gildea and Jurafsky’s (2002) work on semantic role identification in that finding sources often corresponds to finding the filler of the agent role for verbs.
J02-3001
It is important for understanding both newswire and narrative text (Wiebe, 1994), therefore, to appropriately recognize expressions of point of view, and to associate them with their direct and indirect sources.
J94-2004
Note that the acronym ‘pse’ has been used previously with a different meaning (Wiebe, 1994).
J94-2004
