The syntactic relations are generated by the Minipar dependency parser (Lin, 1993).
P93-1016
Probably the most widely used association weight function is (point-wise) Mutual Information (MI) (Church et al., 1990), (Hindle, 1990), (Lin, 1998), (Dagan, 2000), defined by: )()( ),(log),( 2 fPwP fwPfwMI = A known weakness of MI is its tendency to assign high weights for rare features.
J90-1003 P90-1034 P98-2127
Distributional Similarity has been an active research area for more than a decade (Hindle, 1990), (Ruge, 1992), (Grefenstette, 1994), (Lee, 1997), (Lin, 1998), (Dagan et al., 1999), (Weeds and Weir, 2003).
P90-1034 P98-2127 W03-1011
The judgment criterion follows common evaluations of paraphrase acquisition (Lin and Pantel, 2001), (Barzilay and McKeown, 2001), and corresponds to the meaning-entailing substitutability criterion discussed in Section 1.
P01-1008
Typical feature weighting functions include the logarithm of the frequency of word-feature cooccurrence (Ruge, 1992), and the conditional probability of the feature given the word (within probabilistic-based measures) (Pereira et al., 1993), (Lee, 1997), (Dagan et al., 1999).
P93-1024
We considered first an evaluation based on WordNet data as a gold standard, as in (Lin, 1998; Weeds and Weir, 2003).
P98-2127 W03-1011
(Weeds and Weir, 2003)) measure of Lin (1998) as a representative case, and utilized it for our analysis and as a starting point for improvement.
P98-2127 W03-1011
The experiment was conducted using an 18 million tokens subset of the Reuters RCV1 corpus,2 parsed by Lin’s Minipar dependency parser (Lin, 1993).
P93-1016
