Regular languages, especially generated by deterministic nite state automata are widely used in Natural Language processing, for various different tasks (Mohri, 1997).
J97-2003
Similarly, with context free languages, (Abney et al., 1999) showed that converting between two parametrisations of models for stochastic context free languages are equivalent but that there are blow-ups in both directions.
P99-1070
