An overview of di erent methods of approximating CFGs by FAs, along with an experimental comparison, was given by (Nederhof, 2000).
J00-1003
Under certain circumstances, this may be done by carrying over the probabilities from an input probabilistic CFG (PCFG), as shown for the special case of n-grams by (Rimon and Herz, 1991; Stolcke and Segal, 1994), or by training of the FA on a corpus generated by the PCFG (Jurafsky et al., 1994).
E91-1027 P94-1011
Not all PFAs can be determinized, as discussed by (Mohri, 1997).
J97-2003
