While some previous works on subcategorization fi'alne acquisition assumed very little prior knowledge concerning the classification of subcategorization frames \[Brent, 1991; Manning, 1993\], our apllroach assumes the existence of grammar rules Sllecifying subcategorization fi'ame assignment, which enables more accurate learning of subcategorization frames.
P91-1027 P93-1032
\[Goeser, 1992\] Sel)astian Goeser.
C92-1022
of COLING-92, pp.120 126, 1992~ \[Kiyono and 'l)sujii, 1993\] Masaki l(iyono and aun'ichi Tsujii.
E93-1027
To remove unnatural hypotheses, we have introduced the following criteria \[Kiyono and Tsujii, 1993\].
E93-1027
Unlike robusl; parsing \[Mellish, 1989; Goeser, 1992; l)ouglas and I)ale, 1 !)92\] or nou-statisl.ical alll)roach for grallunar a(:lluisil;ioll, our al/proach does Ilol; require a mechanism to detect tile cause of the parsing fail-ure in the sentencial analysis phase and therefore the 'Ilypothesis (~eneral;or' may output ;111 I,he possible hypotheses, l\[owever, the greater part 1)t' hypotheses generated by a simple deductive mechanism are unnatural revisions of the e.xisting grammar.
C92-1022 P89-1013
In order to realize, automatic customizatiou of existing linguistic knowledge to each applicat;ion domain, we proposed a new approach of linguistic knowledge acquisition, which is a combination of symbolic and statistical approaches \[Kiyono and Tsujii, 1993\].
E93-1027
