Restrictions on possible relations are attached to the words, e.g., expressed as valencies in the case of dependency relations, yielding a strictly lexicalized grammar in the sense of Schabes et al.(1988). The individual behavior of words is generalized in terms of word classes which are primarily motivated by governability or phrasal distribution; additional criteria include inflection, anaphoric behavior, and possible modifiers.
C88-2121
First, at the syntactic level, any kind of chart parsing algorithm faces combinatorial problems with noncontiguous grammar specifications (accounting for discontinuous language structures) and, in particular, extraand ungrammatical language input (cf., e.g., Magerman & Weir (1992) for probabilistic and Lee et al.(1995) for symbolic heuristics to cope with that problem).
E95-1031 P92-1006
In a companion paper (Neuhaus & Hahn, 1996), we give an integrated description of the various subprotocols needed for head/modifier search, ambiguity handling, skipping, backtracking, preferential and predictive parsing.
C96-1084
Neuhaus & Hahn (1996)) generates dependency structures for sentences and coherence relations at the text level of analysis.
C96-1084
Also, the provision of conceptual entities which are incrementally generated by the semantic interpretation process supplies the necessary anchoring points for the continuous resolution of textual anaphora and ellipses (Strube & Hahn, 1995; Hahn et al., 1996).
C96-1084 E95-1033
Neuhaus & Hahn (1996)).
C96-1084
Hahn (1996).
C96-1084
Neuhaus & Hahn (1996) for such a protocol extension).
C96-1084
This also distinguishes our approach from another major stream of object-oriented natural language parsing which is almost entirely concerned with implementational aspects of object-oriented programruing, e.g., Habert (1991), Lin (1993) or Yonezawa & Ohsawa (1994).
P93-1016
505 Neuhaus & Hahn (1996)).
C96-1084
Brute-force parsing models such as the primordial soup algorithm (Janssen et al., 1992), at first sight, exhibit a vast potential for parallel execution, since the central operation of building a structure from two independent parts (in our application, e.g., the combination of a head and a single modifier) apparently does not require any centr,'dized control.
C92-1058
Though experiments have been run with packing feature structures and interleaving syntactic and semantic analyses (Dowding et al., 1994), or with the intentional underspecification of logical forms (leaving scope ambiguities of quantifiers and negations underdetermined; cf., e.g., Hobbs (1983) or Reyle (1995)), no conclusive evidences have been generated so far in favor of a general method for efficient, online semantic interpretation.
E95-1001 P83-1009 P94-1016
The lexical distribution of grammatical knowledge one finds in many lexiealized grammar formalisms (e.g., LTAGS (Schabes et al., 1988) or HPSG (Pollard & Sag, 1994)) is still constrained to declarative notions.
C88-2121
