Orthographic features We used the following orthographic features from the original system of Blunsom & Cohn (2006) (below all features are either Boolean indicator functions (b) or real valued (r)): (b) exact string similarity of source-target words; (b) every possible source-target pair of length 3 prefixes; (b) exact string match of length 3 prefixes; (b) exact string match of length 3 suffixes; (r) absolute difference in word lengths; (b) both words are shorter than 4 characters.
P06-1009
Nevertheless, recently such posterior probabilities have been used in SMT word alignment system as an alternative to Viterbi decoding, and helped to improve the performance of such systems (Matusov et al., 2004; Liang et al., 2006).
C04-1032 N06-1014
We considered variations of features 852 that were part of the original system of Blunsom & Cohn(2006),andalsodesignednewfeaturesthatare specific to the problem of MCA.
P06-1009
Moore. 2005.
H05-1011
In this paper we present an MCA algorithm that is based on an extension to the posterior decoding algorithm for MSA called AMAP (Schwartz et al., 2006; Schwartz and Pachter, 2007), with an underlying pairwise alignment model based on the CRF SMT alignment of Blunsom & Cohn (2006).
P06-1009
Blunsom & Cohn (2006) use Viterbi decoding to find an alignment of two sentences given a trained CRF model, a∗ defines argmaxa PΛ(a|Ci,Cj).
P06-1009
We modified the CRF alignment system of Blunsom & Cohn (2006) to support MCA by incorporating the posterior decoding algorithm from Section 3.2 into the existing system.
P06-1009
In this paper we address the problem of multiple citation concept alignment by combining and modifying the CRF based pairwise word alignment system of Blunsom & Cohn (2006) and a posterior decoding based multiple sequence alignment algorithm of Schwartz & Pachter (2007).
P06-1009
Och & Ney (2003) present an overview and comparison of the most common models used for SMT word alignments.
J03-1002
The Viterbi many-to-many pairwise alignments are then generated by combining equivalent pairs of many-to-one alignments using three different standard symmetrization methods forword-alignment—union,intersection,andtherefined method of Och & Ney (2003).
J03-1002
MCA is also related to the problem of word alignment in statistical machine translation (SMT) (Och and Ney, 2003).
J03-1002
In Rada Mihalcea and Ted Pedersen, editors, HLT-NAACL 2003 Workshop: Building and Using Parallel Texts: Data Driven Machine Translation and Beyond, pages1–10, Edmonton, Alberta, Canada, May 31.
W03-0301
As a point of comparison, the SMT community has been evaluating performance of word-alignment systems on an even smaller dataset of 447 pairs of non-overlapping sentences (Mihalcea and Pedersen, 2003).
W03-0301
random fields for word alignment The model of Blunsom & Cohn (2006) is based on a linear chain CRF, which can be viewed as the undirected version of an HMM.
P06-1009
However, to the best of our knowledge only the model of Blunsom & Cohn (2006), which is based on a Conditional Random Field (CRF) (Lafferty et al., 2001), can compute word indices pairs’ directional posterior probabilities, like those computed by the HMM models.
P06-1009
Recently, several authors have described discriminative SMT alignment models (Moore, 2005; Lacoste-Julien et al., 2006; Blunsom and Cohn, 2006).
H05-1011 N06-1015 P06-1009
