Table 1 presents gap insertion F measure for Johnson’s (2002) (denoted J), Gabbard’s (2006) (denoted G), and our (denoted Pres) algorithms on section 23 gold trees, as well as on parses generated by the Charniak and Bikel parsers.
N06-1024 P02-1018
In addition, (Gabbard et al., 2006) provides state-of-the-art results.
N06-1024
Machine learning methods were employed by (Higgins, 2003; Levy and Manning, 2004; Gabbard et al., 2006).
N06-1024 P04-1042
625 3 Evaluation 3.1 Setup We compare our algorithm under a variety of conditions to the work of (Johnson, 2002) and (Gabbard et al., 2006).
N06-1024 P02-1018
The first metric, which was introduced by Johnson (2002), has been widely reported by researchers investigating gap insertion.
P02-1018
Note that Gabbard et al.’s algorithm requires the use of function tags, which are produced using a modified version of the Bikel parser (Gabbard et al., 2006) and a separate software tool (Blaheta, 2003) for the Charniak parser output.
N06-1024
Their performance was comparable to (Johnson, 2002); however, they did not evaluate the impact of the gaps on parser performance.
P02-1018
For example, SuperARV language models (LMs) (Wang and Harper, 2002; Wang et al., 2003), which tightly integrate lexical features and syntactic constraints, have been found to significantly reduce word error in English speech recognition tasks.
W02-1031
This metric differs from that used by Levy and Manning (2004) in that it counts only the dependencies involving gaps, and so it represents performance of the gap insertion algorithm more directly.
P04-1042
Johnson (2002) used corpus-induced patterns to insert gaps into both gold standard trees and parser output.
P02-1018
Dienes and Dubey (2003) recover empty nodes as a preprocessing step and pass strings with gaps to their parser.
W03-1005
The second metric, which was developed by Campbell (2004), scores a gap as correct only when it has the correct gap type and its mother node has the correct nonterminal label and word span.
P04-1082
Campbell (2004) developed a set of linguistically motivated hand-written rules for gap insertion.
P04-1082
We evaluate gap insertion on gold trees from section 23 of the Wall Street Journal Penn Treebank (WSJ) and parse trees automatically produced using the Charniak (2000) and Bikel (2004) parsers.
A00-2018
