We cannot compare accuracies with McCarthy et al.(2004) because use of a thesaurus instead of WordNet means that knowledge of exactly how the thesaurus senses map to WordNet is required.
P04-1036
Since human annotation is both expensive and time intensive, we present an alternative approach of artificially generating thesaurus-sense-tagged data following the ideas of Leacock et al.(1998). Around 63,700 of the 98,000 word types in the Macquarie Thesaurus are monosemous—listed under just one of the 812 categories.
J98-1006
The system (Figure 1) automatically generates a thesaurus (Lin, 1998) using a measure of distributional similarity and an untagged corpus.
P98-2127
McCarthy et al.(2004) automatically determine domainspecific predominant senses of words, where the domain may be specified in the form of an untagged target text or simply by name (for example, financial domain).
P04-1036
Further, the target text must be large enough to learn a thesaurus from (Lin (1998) used a 64million-word corpus), or a large auxiliary text with a sense distribution similar to the target text must be provided (McCarthy et al.(2004) separately used 90-, 32.5-, and 9.1-million-word corpora).
P04-1036 P98-2127
Unlike the McCarthy et al.(2004) system, these methods can be used on relatively small target texts, without the need for a similarly-sensedistributed auxiliary text.
P04-1036
Yarowsky (1992) uses the product of a mutual information–like measure and frequency to identify words that best represent each category in the Roget’s Thesaurus and uses these words for sense disambiguation with a Bayesian model.
C92-2070
Natural language systems can choose to ignore infrequent senses of words or consider only the most dominant senses (McCarthy et al., 2004).
P04-1036
We evaluate the four dominance methods, like McCarthy et al.(2004), through the accuracy of a naive sense disambiguation system that always gives out the predominant sense of the target word.
P04-1036
Note, however, that using a sense inventory other than WordNet will mean that we cannot directly compare performance with McCarthy et al.(2004), as that would require knowing exactly how thesaurus senses map to WordNet.
P04-1036
Pantel (2005) proposes a framework for ontologizing lexical resources.
P05-1016
Categories roughly correspond to coarse senses of a word (Yarowsky, 1992), and the two terms will be used interchangeably.
C92-2070
Note that published thesauri are structurally quite different from the “thesaurus” automatically generated by Lin (1998), wherein a word has exactly one entry, and its neighbors may be semantically related to it in any of its senses.
P98-2127
