Since Gaifman (1965) proved that his projective dependency grammar is weakly equivalent to context-free grammar, Neuhaus and Br¨oker (1997) have shown that the recognition problem for a dependency grammar that can define arbitrary non-projective structures is NP complete, but there are no results for systems of intermediate complexity.
P97-1043
Notable exceptions are Plaehn (2000), where discontinuous phrase structure grammar parsing is explored, and McDonald et al.(2005b), where nonprojective dependency structures are derived using spanning tree algorithms from graph theory.
H05-1066 P05-1012
For example, despite the results of Neuhaus and Br¨oker (1997), McDonald et al.(2005b) perform parsing with arbitrary non-projective dependency structures in O(n2) time.
H05-1066 P05-1012 P97-1043
Most of this work has so far focused either on post-processing to recover non-local dependencies from context-free parse trees (Johnson, 2002; Jijkoun and De Rijke, 2004; Levy and Manning, 2004; Campbell, 2004), or on incorporating nonlocal dependency information in nonterminal categories in constituency representations (Dienes and Dubey, 2003; Hockenmaier, 2003; Cahill et al., 2004) or in the categories used to label arcs in dependency representations (Nivre and Nilsson, 2005).
P02-1018 P03-1055 P04-1040 P04-1041 P04-1042 P04-1082 P05-1013
It should be noted that the proportion of lost dependencies is about twice as high as the proportion of dependencies that are non-projective in themselves (Nivre and Nilsson, 2005).
P05-1013
Moreover, the study of formal grammarsisonly partially relevant for research ondatadriven dependency parsing, where most systems are not grammar-based but rely on inductive inference from treebank data (Yamada and Matsumoto, 2003; Nivre et al., 2004; McDonald et al., 2005a).
H05-1066 P05-1012 P05-1013 W04-2407
Whilethis“surface dependency approximation” (Levy and Manning, 2004) may be acceptable for certain applications of syntactic parsing, it is clearly not adequate as a basis for deep semantic interpretation, which explains the growing body of research devoted to different methods for correcting this approximation.
P04-1042
The pseudo-projective grammar proposed by Kahane et al.(1998) can be parsed in polynomial time and captures non-local dependencies through a form of gap-threading, but the structures generated by the grammar are strictly projective.
P98-1106
