Meanwhile, the semantic annotation of PCTB mainly deals with the predicateargument structure of Chinese verbs in Penn Chinese Proposition Bank (Xue and Palmer, 2003; 22 Xue and Palmer, 2005).
W03-1707
The details of supplementary principles, symbol illustrations, semantic roles, phrasal structures and applications of the CCTB can be found in (CCTB portal; Chen et al., 2003; Chen and Hsieh, 2004; You and Chen, 2004).
W04-1116
The PCTB uses Head-driven Phrase Structure Grammar (HPSG) to create Chinese texts with syntactic bracketing (Xia et al, 2000; Xue et al, 2002).
C02-1145
The details and applications of PCTB can be found in (PCTB portal; Xia et al, 2000; Chiou et al, 2001; Xue et al, 2002; Xue et al, 2005).
C02-1145 H01-1026
In many natural language processing (NLP) applications, such as information retrieval, knowledge discovery, example-based machine translation (EBMT) and text summarization, can benefit with chunks (Le et al., 2003; Munoz et al., 1999; Oliver, 2001; Zhou and Su, 2003).
W03-1711
As per (Brants, 1999), each layer’s chunk bracketing of Cascaded Markov Models is dependent because the output of a lower layer is passed as input to the next higher layer.
E99-1016
The CKIP (Chinese Knowledge Information Processing) Chinese-Treebank (CCTB) and the Penn Chinese Treebank (PCTB) are two of most important Chinese Treebank resources for Treebank-derived NLP tasks in Chinese (CKIP, 1995; Xia et al., 2000; Xu et al., 2000; Li et al., 2004).
W04-1107 W04-1114
For English (Sang and Buchholz, 2000) and Chinese (Li et al., 2004) languages, the top 3 most frequent chunk types are NP, VP and PP chunks.
W04-1107
Among the chunk types, NP chunking is the first to receive the attention (Ramshaw and Marcus, 1995), than other chunk types, such as VP and PP chunking (Veenstra, 1999).
W95-0107
The actual input means the word-segmentation and POS tags all are generated by a selected segmenter and a POS tagger; and (3) High Performance Chunk Bracketing has been reported that the key issue of Chinese parsing (Li et al., 2004).
W04-1107
The brief introductions of the CCTB and the PCTB are given as below (Table 1 is a brief comparison between the CCTB and the PCTB): (1) CCTB: the CCTB is developed in traditional Chinese texts (BIG5 encoded) taken from the Academia Sinica Balanced Corpus 3.0 (ASBC3) at the Academia Sinica, Taiwan (Chen et al., 1996; Chen et al., 1999; Huang et al., 2000, Chen et al., 2003; Chen et al., 2004).
W00-1205
As per the reports (Menzel, 1995; Sang and Buchholz, 2000; Basili and Zanzotto, 2002; Knutsson et al., 2003; Li et al., 2004; Xu et al., 2004; Johnny et al., 2005), there are three important trends in the study of Chinese text chunking and parsing.
W04-1107 W04-1114
