This kind of corpus has served as an extremely valuable resource for computational linguistics applications such as machine translation and question answering (Lee et al., 1997; Choi, 2001), and has also proved useful in theoretical linguistics research (Marcus et al., 1993).
J93-2004
However, most parsers still tend to show low performance on the long sentences (Li et al., 1990; Doi et al., 1993; Kim et al., 2000).
C90-3088 E93-1060 W00-1321
They can be classified into the approaches using the heuristics (Hindle, 1989; Chang et al., 1997) and the approaches using the rules extracted from an already built treebank (Kwak et al., 2001; Lim et al., 2004).
P89-1015
Furthermore, it is too difficult to maintain the consistency of the treebank based on only the annotator (Hindle, 1989; Chang et al., 1997).
P89-1015
The parsing methods using clause-based segmentation have been studied to improve the parsing performance and the parsing complexity (Kim et al., 2000; Lyon and Dickerson, 1997; Sang and Dejean, 2001).
W00-1321
The labeled precision (LP) indicates the ratio of correct candidate constituents from candidate constituents generated by the parser, and the labeled recall (LR) indicates the ratio of correct candidate constituents from constituents in the treebank (Goodman, 1996).
P96-1024
The heuristics are written by the grammarians so that they are so reliable (Hindle, 1989; Chang et al., 1997).
P89-1015
The first approaches are used for Penn Treebank (Marcus et al., 1993) and the KAIST language resource (Lee et al., 1997; Choi, 2001).
J93-2004
