See Rambow (1995) for details.
P95-1021
We are 12 This term is from Schabes and Shieber (1994).
J94-1004
In fact, because there are both situations in which the arrangement of components of the lexically projected structures corresponds to adjoining and situations in which this arrangement is inappropriate, Vijay-Shanker (1992) raises the question of whether the definition of the formalism should limit the arrangement of components of the lexically projected structures, or whether the possible arrangements should be derived from the linguistic theory and from intuitions about the nature of the elementary objects of a grammar.
J92-4004
Rambow, Vijay-Shanker, and Weir (1995), path constraints are called "subsertion-insertion constraints".
P95-1021
118 Rambow, Vijay-Shanker, and Weir D-Tree Substitution Grammars to maximize localization of syntactic dependencies within elementary tree descriptions, thereby avoiding the need for unification during parsing (Carroll et al.1999). Nicolov and Mellish (2000) use DSG as the formalism in a generation application.
E99-1029
Kasper et al.(1995) overcome the problem by making the node label a feature (with all nodes having a default label of no significance).
P95-1013
See Kasper et al.(1995) for details.
P95-1013
Hepple (1998) relates DSG to a system he has previously proposed in which deductions in implicational linear logic are recast as deductions involving only first-order formulas (Hepple 1996).
C96-1091
This perspective on the LTAG formalism was explored in Vijay-Shanker (1992) where, following the principles of d-theory parsing (Marcus, Hindle, and Fleck 1983), LTAG was seen as a system manipulating descriptions of trees rather than as a tree 2 The same analysis holds for wh-movement, but we use topicalization as an example in order to avoid the superficial complication of the auxiliary needed in English questions.
J92-4004 P83-1020
2° Syntactic dependency represents an important linguistic intuition, provides a uniform interface to semantics, and is, as Schabes and Shieber (1994) argue, important in order to support statistical parameters in stochastic frameworks.
J94-1004
Vijay-Shanker. 1992.
J92-4004
D-trees are descriptions of trees, in particular, certain types of expressions in a tree description language such as that of Rogers and Vijay-Shanker (1992).
J92-4004 P92-1010
These examples suggest that the method for compiling an HPSG fragment into TAG-like structures discussed in Kasper et al.(1995) can be simplified by compiling HPSG to a DSG-like framework.
P95-1013
Furthermore, this mechanism makes it difficult to express entire grammars originally formulated in other formalisms in LTAG; for example, when compiling a fragment of HPSG into TAG (Kasper et al.1995). In fact, the compilation produces structures just like those (described) in Figure 3.
P95-1013
This may seem arbitrary at first glance, especially since in many linguistic frameworks and theories it is common to specify linear precedence (LP) separately from syntactic structure (GPSG, HPSG, LFG, ID/LP-TAG \[Joshi 1987\] and FO-TAG \[Becker, Joshi, and Rambow 1991\], various dependency-based formalisms, and so on).
E91-1005
Finally, Vijay-Shanker, Weir, and Rainbow (1995), using techniques developed for UVG-DL (Rainbow 1994a; Becker and Rambow 1995), show that the languages generated by lexicalized DSG can be recognized in polynomial time.
P95-1021
Kasper et al.(1995) consider the tree on the right of Figure 3 to be an auxiliary tree with the VP sibling of the anchor determined to be the foot node.
P95-1013
recent advances in parsing technology are due to the explicit stochastic modeling of dependency information (Collins 1997).
P97-1003
(2) John, Peter gave the book to Figure 15 shows the structures obtained by using the method of Kasper et al.(1995) for compiling an HPSG fragment to TAG-like structures.
P95-1013
For a discussion of V2 in a framework like DSG, see Rambow (1994a) and Rambow and Santorini (1995).
P94-1036 P95-1021
