Relevant work in rhetorical classification for scientific articles, which is the first step toward the production of scientific abstracts, is due to Teufel and Moens (1998), who used statistical approaches borrowed from Kupiec, Pedersen, and Chen (1995).
W98-0307
Since then several methods and theories have been applied, including the use of term frequency ∗ inverse document frequency (TF ∗ IDF) measures, sentence position, and cue and title words (Luhn 1958; Edmundson 1969; Kupiec, Pedersen, and Chen 1995; Brandow, Mitze, and Rau 1995); partial understanding using conceptual structures (DeJong 1982; Tait 1982); bottom-up understanding, top-down parsing, and automatic linguistic acquisition (Rau, Jacobs, and Zernik 1989); recognition of thematic text structures (Hahn 1990); cohesive properties of texts (Benbrahim and Ahmad 1995; Barzilay and Elhadad 1997); and rhetorical structure theory (Ono, Sumita, and Miike 1994; Marcu 1997).
C94-1056 W97-0703 W97-0713
Although the linguistic information for our model has been manually collected, Teufel (1998) has shown how this labor-intensive task can be accomplished in a semiautomatic fashion.
W98-0307
For a complete description of the system and its implementation, the reader is referred to Saggion (2000).
W00-0401
Jing and McKeown (2000) and Jing (2000) propose a cut-and-paste strategy as a computational process of automatic abstracting and a sentence reduction strategy to produce concise sentences.
A00-1043 A00-2024
But in fact, the issue of editing in text summarization has usually been neglected, notable exceptions being the works by Jing and McKeown (2000) and Mani, Gates, and Bloedorn (1999).
A00-1043 A00-2024 P99-1072
For each scenario we present the average information in Table 14 (Saggion and Lapalme [2000c] presented detailed results of this experiment).
W00-0401
Radev and McKeown (1998) have already addressed the issue of information fusion in the context of multidocument summarization in one specific domain (i.e., terrorism): The fusion of information is achieved through the implementation of summary operators that integrate the information of different templates from different documents referring to the same event.
J98-3005
Additional evaluations of SumUM using sentence acceptability criteria and content-based measures of indicativeness have been presented in Saggion and Lapalme (2000b) and Saggion (2000).
W00-0401
Jing (2000) proposes a novel algorithm for sentence reduction that takes into account different sources of information to decide whether or not to remove a particular component from a sentence to be included in a summary.
A00-1043 A00-2024
The idea of 522 Computational Linguistics Volume 28, Number 4 elaborating topics has also been addressed by Mani, Gates, and Bloedorn (1999).
P99-1072
Teufel and Moens (1998) report on a similar work, but this time on the alignment of sentences from author-provided abstracts.
W98-0307
Jing and McKeown (2000) have proposed a rule-based algorithm for sentence combination, but no results have been reported.
A00-1043 A00-2024
Examples of sentences generated by the system have been presented in Saggion and Lapalme (2000a).
W00-0401
Our work in sentence reformulation is different from cut-and-paste summarization (Jing and McKeown 2000) in many ways.
A00-1043 A00-2024
This method of evaluation has already been used in other summarization evaluations such as Edmundson (1969) and Marcu (1997).
W97-0713
