tion was Gandrabur and Foster (2003). Their confidence measures consist of a com-
W03-0413
Zens and Ney (2006) presented an extension of the word posterior probabili-
W06-3110
machine translation (Gandrabur and Foster 2003; Ueffing and Ney 2005a)
H05-1096 W03-0413
Zens, Richard and Hermann Ney. 2004.
N04-1033
is the “empty” source word (Brown et al. 1993). The probabilities p(e|f
J93-2003
Zens, Richard and Hermann Ney. 2006.
W06-3110
generated by the translation system (Ueffing, Och, and Ney 2002; Zens and Ney 2005).
H05-1096 W02-1021 W05-0834
(Gandrabur and Foster 2003; Ueffing and Ney 2005a).
H05-1096 W03-0413
Chiang, David. 2005. A hierarchical
P05-1033
of-the-art phrase-based translation approach as described in Zens and Ney (2004).
N04-1033
translations (Akiba et al. 2004), or the word confidence scores can be used
C04-1047
lation (Gandrabur and Foster 2003; Ueffing, Macherey, and Ney 2003; Blatz et al.2004; Quirk 2004). In this article, we will develop a sound theoretical framework for
W03-0413
confidence features has been suggested (Gandrabur and Foster 2003; Blatz et al. 2004;
W03-0413
Tillmann, and Ney 1999; Koehn, Och, and Marcu 2003; Tillmann 2003; Bertoldi et al.2004; Vogel et al. 2004; Zens and Ney 2004; Chiang 2005). A more detailed description of
J04-4002 N03-1017 N04-1033 P03-1021 P05-1033 W03-1001 W05-0834
Akiba et al. (2004) reported the application of confidence measures to the selection
C04-1047
Tillmann, Christoph. 2003. A projection
W03-1001
be optimized with respect to some evaluation criterion (Och 2003). Nevertheless, this
P03-1021
(Blatz et al. 2003, 2004; Gandrabur and Foster 2003; Ueffing, Macherey, and Ney 2003;
W03-0413
Ueffing, Nicola and Hermann Ney. 2005a.
H05-1096
Zens, Richard and Hermann Ney. 2005.
W05-0834
The alignment template system (Och and Ney 2004) (denoted as AT in the
J04-4002
Och, Franz J. 2003. Minimum error rate
P03-1021
target words as first described in Ueffing and Ney (2005b). In contrast to the approaches
H05-1096
Richard Zens, and Hermann Ney. 2005.
W05-0834
Och, Franz J. and Hermann Ney. 2004. The
J04-4002
are optimized with respect to some evaluation criterion (Och 2003) such as BLEU
P03-1021
and compare it to the other types of confidence measures. Ueffing and Ney (2005a)
H05-1096
(Jayaraman and Lavie 2005), or the sentence confidence value can be
P05-3026
(Gandrabur and Foster 2003; Ueffing, Macherey, and Ney 2003). Among them were also
W03-0413
Ueffing, Nicola and Hermann Ney. 2005b.
H05-1096
Gandrabur, Simona and George Foster. 2003.
W03-0413
(Papineni et al. 2002), and NIST score (NIST 2002) is given in Table 4. We see that
P02-1040
