Pitler, E. and A. Nenkova. 2008. Revisiting
D08-1020
1991; Pitler and Nenkova 2008). Third, some features other than word frequencies are
D08-1020
The first classification method followed that of Schwarm and Ostendorf (2005). The
P05-1065
. Pitler and Nenkova (2008) are likely to have used subtraction within their
D08-1020
Recently, Pitler and Nenkova (2008) presented an impressive verification of the effects of
D08-1020
classification modeling, as reported in Collins-Thompson and Callan (2004) and Si
N04-1025
Schwarm, S. E. and M. Ostendorf. 2005.
P05-1065
At the beginning of this project, we tried to apply Schwarm and Ostendorf (2005)
P05-1065
Barzilay, R. and M. Lapata. 2008. Modeling
J08-1001
SVM (Schwarm and Ostendorf 2005) and the authors also studied the effect of statistical
P05-1065
Collins-Thompson, K. and J. Callan. 2004.
N04-1025
and Collins-Thompson and Callan (2004). Because the request covered multiple lan-
N04-1025
been proposed (Klare 1963; DuBay 2004a, 2004b; Schwarm and Ostendorf 2005; Pitler
P05-1065
comparator generated by an SVM. In addition, Pitler and Nenkova (2008) presented a
D08-1020
words also counts with respect to readability (Collins-Thompson and Callan 2004).
N04-1025
(Barzilay and Lapata 2008) and language learning. Readability in this article signifies
J08-1001
