Sarkar,Anoop. 2001. Applying co-training
N01-1023
Titov,Ivan and James Henderson. 2007b. A
W07-2218
Nakagawa 2007; Smith and Eisner 2008) as well as exact solutions through integer linear
D07-1100 D08-1016
Labeled parsing accuracy for top-scoring systems at CoNLL-X (Buchholz and Marsi 2006).
W06-2920
Hall,Keith. 2007. K-best spanning tree
D07-1097 P07-1050
Smith,David A. and Jason Eisner. 2008.
D08-1016
(Maruyama 1990). Common to all theories is the notion of directed syntactic depen-
P90-1005
Crammer,and Pereira 2005; McDonald,Lerman,and Pereira 2006). For the guided
E06-1011 W06-2932
colleagues (McDonald,Crammer,and Pereira 2005; McDonald et al. 2005; McDonald
H05-1066 P05-1012
McDonald,Ryan and Giorgio Satta. 2007.
D07-1013 W07-2216
directly have been explored by Attardi (2006) and Nivre (2007,2009),among others.
D07-1096 N07-1049 N07-1050 P09-1040
Kudo,Taku and Yuji Matsumoto. 2002.
W02-2016
McDonald,Ryan and Joakim Nivre. 2007.
D07-1013 D07-1096 N07-1050 W07-2216
as observed by Buchholz and Marsi (2006),it is striking that recent work on data-driven
W06-2920
characterization ﬁts the approach of Zhang and Clark (2008) and Huang
D08-1059
Nivre,Joakim and Jens Nilsson. 2005.
P05-1013
Zabokrtsk`y 2005),or both (McDonald 2006). Of particular note is past work
E06-1011 W06-2932
Huang,Liang and David Chiang. 2005.
W05-1506
Sagae,Kenji and Alon Lavie. 2006. Parser
N06-2033
Maruyama,Hiroshi. 1990. Structural
P90-1005
C¸ akıcı,and Meza-Ruiz (2006),Nakagawa (2007),Smith and Eisner (2008),and Martins,
D07-1100 D08-1016
Huang,Liang and Kenjie Sagae. 2010.
P10-1110
Nivre,Joakim. 2007. Incremental
D07-1096 N07-1050
Ding,Yuan and Martha Palmer. 2004.
W04-1513
Nivre,Hall,and Nilsson (2004),and Nivre and Nilsson (2005) showed how the restric-
P05-1013 W04-2407
Duan,Xiangyu,Jun Zhao,and Bo Xu. 2007.
D07-1098
(McDonald,Lerman,and Pereira 2006) (Nivre et al. 2006)
E06-1011 W06-2932 W06-2933
from the 2006 and 2007 CoNLL shared tasks (Buchholz and Marsi 2006; Nivre et al.2007)—has led to a boom in research on data-driven dependency parsing. Making sense
D07-1096 N07-1050 W06-2920
Meza-Ruiz 2006; Carreras 2007; Koo et al. 2007; Nakagawa 2007; Smith and Smith 2007).
D07-1014 D07-1015 D07-1100 D07-1101
Penn Treebank (Marcus,Santorini,and Marcinkiewicz 1993). A dependency graph of
J93-2004
Huang and Sagae (2010) go even further and show how transition-based parsing can be
P10-1110
in conjunction with approximate inference. Additionally,Riedel and Clarke (2006) and
W06-1616 W06-2934
(McDonald,Crammer,and Pereira 2005; Koo et al. 2007; Smith and Smith 2007),which
D07-1013 D07-1014 D07-1015 H05-1066 P05-1012 W07-2216
dency parsing by McDonald (2006),who trained an instance of MSTParser using fea-
E06-1011 W06-2932
McDonald,Ryan. 2006. Discriminative
E06-1011 W06-2932
tures generated by the parsers of Collins (1999) and Charniak (2000),which improved
A00-2018
Going beyond arc-factored models,McDonald and Pereira (2006) presented a
E06-1011 W06-2932
Martins,Smith,and Xing (2009) integrate global features and maintain exact inference
P09-1039
Smith,David A. and Noah A. Smith. 2007.
D07-1014
Cheng,Asahara,and Matsumoto 2006),Nivre (Nivre,Hall,and Nilsson 2004; Nivre and
W04-2407 W06-2927
and Pereira (2006),Hall (2007),Nakagawa (2007),and Smith and Eisner (2008) attempt
D07-1097 D07-1100 D08-1016 P07-1050
Johansson and Nugues 2007; Duan,Zhao,and Xu 2007; Titov and Henderson 2007a,
D07-1098 W07-2218
by changing the underlying model structure directly. For example,Hall (2007),Riedel,
D07-1097 P07-1050
Carreras,Xavier. 2007. Experiments with a
D07-1101
Zhang and Clark (2008) propose a parsing system that uses global learning coupled
D08-1059
Charniak,Eugene. 2000. A maximum-
A00-2018
McDonald et al. (2005) showed that this problem is equivalent to ﬁnding the highest
H05-1066 P05-1012
over anything larger than arcs (McDonald and Satta 2007). Thus,graph-based parsing
D07-1013 W07-2216
Nakagawa,Tetsuji. 2007. Multilingual
D07-1100
Nivre,Joakim. 2009. Non-projective
P09-1040
mate inference through beam search,and Huang and Sagae (2010) has shown how a
P10-1110
Noah A. Smith,and Eric P. Xing. 2008.
D08-1016
approximate non-factored parsing systems (McDonald and Pereira 2006; Hall 2007;
D07-1013 D07-1097 E06-1011 P07-1050 W06-2932 W07-2216
ranging from machine translation (Ding and Palmer 2004) to ontology construction
W04-1513
errors through the work of Sagae and Lavie (2006). However,in that work an arc-based
N06-2033
rived from the IBM models,by Florian et al. (2004),who trained classiﬁers on auxiliary
N04-1001
details about parameter settings,we again refer to Nivre et al. (2006) and the companion web site
W06-2933
Titov,Ivan and James Henderson. 2007a.
W07-2218
McDonald,Lerman,and Pereira (2006),which uses pairwise arc scoring and approx-
E06-1011 W06-2932
shared task (Buchholz and Marsi 2006). In this section we ﬁrst describe the task and the
W06-2920
work has previously been published partially in McDonald and Nivre (2007) and Nivre and
D07-1013 D07-1096 N07-1050 W07-2216
voting methods used by Sagae and Lavie (2006). In this situation,the oracle accuracy
N06-2033
Pereira (2006) (graph-based) and Nivre et al. (2006) (transition-based),which exhibit
W06-2933
been applied to syntactic parsing by Sarkar (2001) and Steedman et al. (2003),among
N01-1023
either generative (Titov and Henderson 2007a,2007b) or conditional (Duan,Zhao,
W07-2218
The CoNLL-X shared task (Buchholz and Marsi 2006) was a large-scale evaluation
W06-2920
Riedel,Sebastian and James Clarke. 2006.
W06-1616 W06-2934
the groups of Matsumoto (Kudo and Matsumoto 2002; Yamada and Matsumoto 2003;
W02-2016
found in Nivre et al. (2006) and on the companion web site.
W06-2933
Nilsson 2005; Nivre et al. 2006),and others (Attardi 2006; Attardi and Ciaramita 2007;
D07-1096 N07-1049 N07-1050 W06-2933
reasons and often does not affect performance signiﬁcantly (see McDonald [2006] for
E06-1011 W06-2932
inference algorithms from the graph-based parsing literature (McDonald et al. 2005).
H05-1066 P05-1012
technique was used by Hall et al. (2007) to combine six transition-based parsers in the
D07-1097 P07-1050
and Pereira 2006; McDonald,Lerman,and Pereira 2006) and others (Riedel,C ¸ akıcı,and
E06-1011 W06-2932
Nakagawa (2007),and others. The analysis presented in this section
D07-1100
can partially alleviate this problem,and both Carreras (2007) and Koo et al. (2010)
D07-1101 P10-1001
Hollingshead,Kristy and Brian Roark. 2007.
P07-1120
et al. (2008) and Martins,Smith,and Xing (2009) report additional improvements.
P09-1039
the kind proposed by Sagae and Lavie (2006),making the weights depend
N06-2033
and Sagae (2010),and the latter that of Riedel and Clarke (2006),
N06-2033 W06-1616 W06-2934
and Xu 2007; Johansson and Nugues 2007). In addition,Zhang and Clark (2008) has
D08-1059
Buchholz,Sabine and Erwin Marsi. 2006.
W06-2920
2006) and a log-linear arc-labeler (Berger,Pietra,and Pietra 1996) regularized with a
J96-1002
Henderson,John C. and Eric Brill. 1999.
W99-0623
at combining phrase-structure parsers (Henderson and Brill 1999),dependency parsers
W99-0623
associated with the pioneering work of Eisner (Eisner 1996),as well as McDonald and
C96-1058
McDonald,Ryan and Fernando Pereira. 2006.
E06-1011 W06-2932
Parser uses on-line algorithms (McDonald,Crammer,and Pereira 2005; Crammer et al.2006) and MaltParser uses support vector machines (Cortes and Vapnik 1995). The
E06-1011 H05-1066 P05-1012 W06-2932
programming (Riedel,C¸ akıcı,and Meza-Ruiz 2006; Martins,Smith,and Xing 2009).
P09-1039 W06-1616 W06-2934
languages (Buchholz and Marsi 2006; Nivre et al. 2007). Thus,the example in Figure 1
D07-1096 N07-1050 W06-2920
Eisner,Jason M. 1996. Three new
C96-1058
Zhang,Yue and Stephen Clark. 2008.
D08-1059
parsers in the spirit of pipeline iteration (Hollingshead and Roark 2007). For example,
P07-1120
dependency parser (McDonald,Crammer,and Pereira 2005; McDonald and Pereira
H05-1066 P05-1012
systems. McDonald,Crammer,and Pereira (2005) show that a rich feature set over
H05-1066 P05-1012
