Ritchie, Graeme (1989).
E89-1007
Koskenniemi, Kimmo (1984).
P84-1038
(This is a slight generalization of the presentation in Ritchie 1989).
E89-1007
44 Graeme Ritchie Languages Generated by Two-Level Morphological Rules In the following illustrative example of a two-level morphological rule (taken from Ritchie et al.1987), angle brackets indicate sequences of pairs and braces indicate alternatives; also, C, V, C2, and = represent subsets of the relevant symbol alphabets and + is an abstract symbol occurring in certain lexical forms.
J87-3008
However, they do not need to rely on the additional stipulation given in 6, since the use of a surface null will give the desired effect when considering the entire mapping from lexical forms to surface form, with explicit null symbols being removed in the manner outlined in Section 2 above (see Ritchie 1989 for a formal definition of this phase).
E89-1007
1. Background Koskenniemi (1983a, 1983b, 1984) proposed a rule-system for describing morphological regularities in a language, depending centrally on the idea of matching two sequences of symbols--a lexical string (made up of the lexical forms of morphemes) and a surface string (the sequence of characters in the normal, inflected, form of the word).
P84-1038
Koskenniemi 1983a, 1983b; Karttunen 1983) is via sublexicons for different lexeme classes, with cross-pointers indicating allowable sequences of lexemes (a formal definition of this can be found in Ritchie 1989).
E89-1007
We shall ignore this issue here (but see Ritchie 1989 and Ritchie et al.1991 for a formal statement of two possible lexical interfaces).
E89-1007
Fuller examples of the use of two-level rules can be found in Koskenniemi (1983a) and Ritchie et al.(1987, 1991).
J87-3008
