Karttunen, Kaplan, and Zaenen (1992), for example, argued that certain French morphological patterns can be better described as the composition of two separate two-level grammars rather than as a single one.
C92-1025
However, the obvious extensions of these properties do hold for the general case, and they may be useful in developing a formal understanding of autosegmental phonological and morphological theories (for an illustration, see Kay 1987).
E87-1002
Ritchie (1992) summarizes aspects of this analysis as presented by Kaplan (1988).
J92-1003
Karttunen, Lauri, and Beesley, Kenneth (1992).
C92-1025
Ritchie et al.(1992) describe a program that interprets this notation by introducing and manipulating labels assigned to the states of component finitestate machines.
J92-1003
Karttunen and Beesley (1992, p.
C92-1025
This is the sort of arrangement that Karttunen et al.(1992) discuss.
C92-1025
We are also encouraged by initial successes in adapting these techniques to the autosegmental formalism described by Kay (1987).
E87-1002
Karttunen, Koskennienni, and Kaplan 1987; Karttunen and Beesley 1992) the mathematical techniques we presented above for the analysis of rewriting systems were used to translate this notation into the equivalent regular relations and corresponding transducers, and thus to create a compiler for a more intuitive and more tractable two-level rule notation.
C92-1025
Kay, Martin (1987).
E87-1002
Ritchie (1992), for example, also proved that the "languages" generated by two-level grammars with regular contexts are closed under intersection, but this result does not hold if a grammar's language is taken to be its outer relation.
J92-1003
It is interesting to note that for much the same reason, Ritchie (1992) also made crucial use of two-level boundary-context rules to prove that the relations denoted by Koskenniemi's (1985) two-level grammars are also coextensive with the regular relations.
J92-1003
As we mentioned before, the two-level grammars with boundary-context rules are the ones that Ritchie (1992) showed were complete for the regular relations.
J92-1003
