Veronis (1988) presents a method for handling quite complex combinations of typographical and phonographic errors (phonographic errors are the kind usually made by language learners using computer-aided instruction).
C88-2146
More recently, Bowden and Kiraz (1995) have used a multitape morphological analysis technique for spelling correction in Semitic languages which, in addition to insertion, deletion, substitution, and transposition errors, allows for various language-specific errors.
P95-1004
In some cases, however, the proposed approach may not be efficient and may be augmented with language-specific heuristics: For instance, in spelling correction, users (at least in Turkey, as indicated by our error model \[Oflazer and Gfizey 1994\]) usually replace non-ASCII characters with their nearest ASCII equivalents because of inconveniences such as nonstandard keyboards, or having to input the non-ASCII characters using a sequence of keystrokes.
A94-1024 A94-1037
Two-level transducers (Karttunen and Beesley 1992; Karttunen, Kaplan, and Zaenen 1992) provide a suitable model for the application of error-tolerant recognition.
C92-1025
The approach presented in Oflazer and G6zey 1994 generates a valid sequence of the lexical forms of root and suffixes and uses a separate morphographemic component that implements the two-level rules to derive surface forms.
A94-1024 A94-1037
Oflazer and G6zey (1994) present a two-level morphology approach to spelling correction in agglutinative languages using a coarser morpheme-based morphotactic description rather than the finer lexi8 Ranking is dependent on the language, the application, and the error model.
A94-1024 A94-1037
Our earlier study of an error model developed for spelling correction in Turkish indicated similar results (Oflazer and G/izey 1994).
A94-1024 A94-1037
Aduriz et al.(1993) present a two-level morphology approach to spelling correction in Basque.
E93-1057
Under these circumstances, one may use language-specific heuristics first, before resorting to error-tolerant recognition, along the lines suggested by morphological-analysis-based approaches (Aduriz et al.1993; Bowden and Kiraz 1995).
E93-1057 P95-1004
Error-tolerant recognition can be used in many applications that are based on finite-state recognition, such as morphological analysis, spelling correction, or even tagging with finite-state models (Voutilainen and Tapanainen 1993; Roche and Schabes 1995).
E93-1046 J95-2004
82 Kemal Oflazer Error-tolerant Finite-state Recognition okutulma => ((CAT okutulma => ((CAT okutulan => ((CAT okutulana => ((CAT okutulsa => ((CAT okutula => VERB)(RODT oku)(VOICE CAUS)(VOICE PASS)(SENSE NEG) (MOOD IMP)(AGR=2SG)) VERB)(ROOT oku)(VOICE CAUS)(VOICE PASS)(SENSE POS) (CONV NOUN MA)(TYPE INFINITIVE) (AGE 3SG)(POSS NONE)(CASE NOM)) VEKB)(ROOT oku)(VOICE CAUS)(VOICE PASS)(SENSE POS) (CONV ADJ YAN)) VERB)(ROOT oku)(VOICE CAUS)(VOICE PASS)(SENSE POS) (CONV ADJ YAN)(CONV NOUN)(AGR 3SG)(POSS NONE)(CASE DAT)) VERB)(ROOT oku)(VOICE CAUS)(VOICE PASS)(SENSE POS) (MOOD COND)(AGE 3SG)) (CAT VERB)(ROOT oku)(VOICE CAUS)(VOICE PASS)(SENSE POS) (MOOD OPT)(AGR 3SG)) In an application context, the candidates that are generated by such a morphological analyzer can be disambiguated or filtered to a certain extent by constraint-based tagging techniques (see Oflazer and Kuru6z 1994; Voutilainen and Tapanainen 1993) that take into account syntactic context for morphological disambiguation.
A94-1024 A94-1037 E93-1046 E93-1066
References Aduriz, I., et al.(1993). A Morphological Analysis-based Method for Spelling Correction.
E93-1057
In the context of spelling correction, error-tolerant recognition can universally be applied to the generation of candidate correct forms for any language, provided it has a word list comprising all inflected forms, or its morphology has been fully described by automata such as two-level finite-state transducers (Karttunen and Beesley 1992; Karttunen, Kaplan, and Zaenen 1992).
C92-1025
• 80 Kemal Oflazer Error-tolerant Finite-state Recognition words and is a re-implementation, using Xerox two-level transducer technology (Karttunen and Beesley 1992), of an earlier version of the same description by the author (Oflazer 1993) (using the PC-KIMMO environment \[Antworth 1990\]).
C92-1025 E93-1066
Full-scale descriptions using this approach already exist for a number of languages such as English, French, German, Turkish, and Korean (Karttunen 1994).
C94-1066
