For this process, we use LONCBOW, a domain-independent discourse planner originally developed as part of a project aimed at generating tutorial explanations (Young and Moore 1994).
W94-0302
Details on centering theory and its relation to discourse structure can be found in Grosz, Joshi, and Weinstein (1995), Walker (1993), Walker, Iida, and Cote (1994), Grosz and Sidner (1993), and Gordon, Grosz, and Gilliom (1993); for lack of space in this paper, we only provide a minimal introduction to the basic terminology of centering theory.
J94-2003 J95-2003
The central tenet in centering theory is that discourse coherence of a text span increases (and a reader's cognitive load decreases) proportionately to the extent that discourse within the span follows two fundamental centering constraints (Grosz, Joshi, and Weinstein 1995).
J95-2003
It describes an implemented system that integrates two robust systems: SAGE--an intelligent graphics presentation system (Roth et al.1994), and a natural language generator, consisting of a text planner (Young and Moore 1994; Young 1997), a microplanner implementing tactical decisions, and a sentence realizer (Elhadad and Robin 1992).
W94-0302
There are two ways of dealing with this issue: (i) The system could apply iterative refinements of the referring expressions generated by the planner, as done in the local brevity algorithm (Reiter 1990).
P90-1013
The POSTGRAPttE system (Fasciano 1996; Fasciano and Lapalme 1996) is the closest related research effort.
W96-0406
Grosz and her colleagues suggest that a competent generation system should apply the constraint on movement by planning ahead in an attempt to minimize the number of SHIFTS in a locally coherent discourse segment (Grosz, Joshi, and Weinstein 1995).
J95-2003
This case is not mentioned in Grosz, Joshi, and Weinstein (1995).
J95-2003
In particular, for generating referring expressions (including pronominalization) (see Dale \[1992\], Appelt \[1985\], and Maybury \[1991\]), for deciding when to combine clauses (subordination and aggregation) (see Derr and McKeown \[1984\]), and finally for choosing appropriate inter/intraclause orderings, namely, ordering between clauses and between their arguments (see Maybury \[1991\], Hovy and McCoy \[1989\], and McKeown \[1985\]).
P84-1065
Focus (e.g., Sidner 1979; Grosz 1977) and centering (e.g., Grosz, Joshi, and Weinstein 1995) models are attempts at explaining linguistic and atttentional factors that contribute to local coherence among utterances.
J95-2003
In the general case, aggregation in natural language is a very difficult problem (Dalianis 1996; Shaw 1995; Huang and Fiedler 1996).
P95-1053 W96-0403
For a complete definition of the algorithm, its computational properties, and its utility for discourse planning, see Young, Pollack, and Moore (1994), and Young and Moore (1994).
W94-0302
Although several projects have focused on the question of how such intelligent graphical presentations can be automatically generated (e.g., Casner 1991; Mackinlay 1986; Roth and Hefley 1993; Kerpedjiev 1992), they have not addressed the problem of generating the accompanying textual explanations.
A92-1007
Research has also focused on issues regarding the generation of coordinated presentations in applications where the graphics are familiar, or possess an obvious mapping between the data set and a graphical image (e.g., weather maps \[Kerpedjiev 1992\] and network diagrams \[Marks and Reiter 1990\]).
A92-1007 P90-1013
As in Grosz, Joshi, and Weinstein (1995), we assume DS fixed and we drop it as an argument.
J95-2003
