These operations are not domain-specific and are similar to those of previous aggregation components (Rambow and Korelsky, 1992; Shaw, 1998; Danlos, 2000), although the various MERGE operations are, to our knowledge, novel in this form.
A92-1006 W98-1415
For these reasons, Oh and Rudnicky (2000) use a101 -gram models and Ratnaparkhi (2000), maximum entropy to choose templates, using hand-written rules to score different candidates.
A00-2026 W00-0306
Mellish et al.(1998) investigate the problem of determining a discourse tree for a set of elementary speech acts which are partially constrained by rhetorical relations.
W98-1411
In the second phase, the sentence plan ranker (SPR) ranks sentence plans generated by the SPG, and then selects the top-ranked output as input to the surface realizer, RealPro (Lavoie and Rambow, 1997).
A97-1039
The representations used by Danlos (2000), Gardent and Webber (1998), or Stone and Doran (1997) are similar, but do not (always) explicitly represent the clause combining operations as labeled nodes.
P97-1026
2 1 3imp−confirm(month) request(time) soft−merge−general imp−confirm(dest−city) imp−confirm(orig−city) imp−confirm(day) soft−merge soft−merge−general soft−merge−general Figure 5: Alternative 0 Sentence Plan Tree Figure 2 shows some of the realizations of alternative sentence plans generated by our SPG for utterance Sys3The sp-tree is inspired by (Lavoie and Rambow, 1998).
P98-1118
Work Previous work in sentence planning in the natural language generation (NLG) community uses hand-written rules to approximate the distribution of linguistic phenomena in a corpus (see (Shaw, 1998) for a recent example with further references).
W98-1415
Other related work deals with discourse-related aspects of sentence planning such as cue word placement (Moser and Moore, 1995), clearly a crucial task whose integration into our approach we leave to future work.
P95-1018
