We analyze our results using syntactic features extracted from a parse tree generated by Collins parser (Collins, 1997) and compare those to models built using features extracted from FrameNet’s human annotations.
P97-1003
(Berger et al., 1996).
J96-1002
We are looking at ways to include such information either by using alternative parsers (Hermjakob, 1997) or as a post processing task (Blaheta and Charniak, 2000).
A00-2031
2.1 2.2 Training (32,251 sentences), development (3,491 sentences), and held out test sets (3,398 sentences) were generated from the June 2002 FrameNet release following the divisions used in Gildea and Jurafsky (2000) 1. Because human-annotated syntactic information could only be obtained for a subset of their data, the training, development, and test sets used here are approximately 10% smaller than those used in Gildea and Jurafsky (2000).
P00-1065
Following Gildea and Jurafsky (2000), automatic extraction of grammatical information here is limited to the governing category of a Noun Phrase.
P00-1065
Due to data sparsity issues, we do not calculate this model directly, but rather, model various feature combinations as described in Gildea and Jurafsky (2000).
P00-1065
We use the YASMET ME package (Och, 2002) to train an approximation of the model below: P(r| pt, voice, position, target, gf, h) Here r indicates the element type, pt the phrase type, gf the grammatical function, h the head word, and target the target predicate.
P02-1038
The YASMET MEtagger was used to apply an ngram tag model to the classification task (Bender et al., 2003).
E03-1055
Following recent successes using it for many NLP tasks (Och and Ney, 2002; Koeling, 2000), we use ME to implement a Frame Element classifier.
P02-1038 W00-0729
Gildea and Jurafsky (2000) describe a system that uses completely syntactic features to classify the Frame Elements in a sentence.
P00-1065
To our knowledge, Gildea and Jurafsky (2000) is the only work that uses FrameNet to build a statistical semantic classifier.
P00-1065
We extend Gildea and Jurafsky (2000)’s initial effort in three ways.
P00-1065
As a further analysis, we have examined the performance of our base ME model on the same test set as that used in Gildea and Jurafsky (2000).
P00-1065
