Two alignment procedures are implemented: one is the widely used dynamic programming procedure that derives monotone alignment of sentence segments (Gale and Church, 1991); the other is divisive clustering procedure that begins by finding coarse alignments that are then iteratively refined by successive binary splitting (Deng et al., ).
P91-1023
In published experiments we have found that MTTK generates alignments of quality comparable to those generated by GIZA++, where alignment quality is measured both directly in terms of Alignment Error Rate relative to human word alignments and indirectly through the translation performance of systems constructed from the alignments (Deng and Byrne, 2005).
H05-1022
MTTK provides implementations of various alignment, models including IBM Model-1, Model-2 (Brown et al., 1993), HMM-based word-to-word alignment model (Vogel et al., 1996; Och and Ney, 2003) and HMM-based word-to-phrase alignment model (Deng and Byrne, 2005).
C96-2141 H05-1022 J03-1002 J93-2003
Atthefinestlevel, thisinvolvesthealignment of words and phrases within two sentences that are known to be translations (Brown et al., 1993; Och and Ney, 2003; Vogel et al., 1996; Deng and Byrne, 2005).
C96-2141 H05-1022 J03-1002 J93-2003
There are systems available for these purposes, notably the GIZA++ (Och and Ney, 2003) toolkit and 265 ! " # $ % & ' (), * +, $ % '-,./ 01 &2 . It is necessary to resolutely remove obstacles in rivers and lakes . 3 4 56 78 9:, ;< => . 4 . It is necessary to strengthen monitoring and forecast work and scientifically dispatch people and materials . ! ?@ AB CD, EFGH IJ 9 : K> . It is necessary to take effective measures and try by every possible means to provide precision forecast . L M ! NO PQ RS 9: FT, A U*V W XY() . Before the flood season comes, it is necessary to seize the time to formulate plans for forecasting floods and to carry out work with clear G6aG8fG90G95G8cG9aG8c G6cG95G8eG93G90G9aG8f Figure 1: Chinese/English Parallel Corpus Aligned at the Sentence, Word, and Phrase Levels: horizontal lines denote the segmentations of a sentence alignment and arrows denote a word-level mapping.
J03-1002
A novel computation performed by MTTK is the genera266 tion of model-based phrase pair posterior distributions (Deng and Byrne, 2005), which plays an important role in extracting a phrase-to-phrase translation probabilities.
H05-1022
Model complexity increases gradually to Model-2, and then HMM-based word-to-word alignment model, and finally to HMM-based word-to-phrase alignment model (Deng and Byrne, 2005).
H05-1022
Alignment quality can be further improved when the chunking procedure is based on translation lexicons from IBM Model-1 alignment model (Brown et al., 1993).
J93-2003
Another task is the identification and alignment of sentence-level segments within document pairs that are known to be translations (Gale and Church, 1991); this is referred to as sentence-level alignment, although it may also involve the alignment of sub-sentential segments (Deng et al., ) as well as the identification of long segments in either document which are not translations.
P91-1023
