Conversely, the PP headed by “because” modifying the same verb is an adjunct, and can safely be deleted if unimportant.3 Also, as discussed in (Klein and Manning, 2003), POS annotation can be useful as a means of backing off to more frequently occurring head-modifier POS occurrences(e.g.,VBD-IN)whenspecificbilexicalco2Details about the SCFG extraction procedure are given in Section 4.
P03-1054
Given the need to ensure grammatical sentences, a number of researchers have used syntax-directed approaches that perform transformations on the output of syntactic parsers (Jing, 2000; Dorr et al., 2003).
A00-1043 W03-0501
We also exploited more general tree productions known as synchronous tree substitution grammar (STSG)rules,inanapproachquitesimilarto(Turner and Charniak, 2005).
P05-1022 P05-1036
(2) We provide a comprehensive analysis of the impact of different Markov orders for sentence compression, similarly to a study done for PCFGs (Klein and Manning, 2003).
P03-1054
To achieve the above desiderata for better SCFG probability estimates—i.e., reduce the amount of sister annotation within each SCFG production, by conditioning deletions on a context smaller than an entire right-hand side, and at the same time increase the amount of ancestor and descendent annotation through parent (or ancestor) annotation and lexicalization—we follow the approach of (Collins, 1999; Klein and Manning, 2003), i.e., factorize n-ary grammar productions into products of n right-hand side probabilities, a technique sometimes called Markovization.
P03-1054
Similarly to K&M and many successful syntactic parsers (Collins, 1999; Klein and Manning, 2003), our sentence compression system is generative, and attempts to find the optimal compression ˆc by estimating the following function:1 ˆc = argmax c∈C braceleftbigg p(c|f) bracerightbigg = argmax c∈C braceleftbigg p(f,c) bracerightbigg (1) If τ(f,c) is the set of all tree pairs that yield (f,c) according to some underlying SCFG, we can estimate the probability of the sentence pair using: p(f,c) = summationdisplay (pif,pic)∈τ(f,c) P(pif,pic) (2) We note that, in practice (and as in K&M), Equation 2 is often approximated by restricting τ(f,c) to a unique full tree ˆpif, the best hypothesis of an off-the-shelf syntactic parser.
P03-1054
Some of them (Knight and Marcu, 2000; Turner and Charniak, 2005) take an empirical approach, relying on formalisms equivalent to probabilistic synchronous context-free grammars (SCFG) ∗This material is based on research supported in part by the U.S.
P05-1022 P05-1036
Charniak. 2005.
P05-1022
Given a tree pair (f,c), whose respective parses (pif,pic) were generated by the parser described in (Charniak and Johnson, 2005), the goal is to transform the tree pair into SCFG derivations, in order to build relative frequency estimates for our Markovized models from observed SCFG productions.
P05-1022
One successful recent approach (McDonald, 2006) combines a discriminative framework with a set of features that capture information similar to the K&M model.
E06-1038
Indeed, current SCFG models such as K&M have no direct way of preventing highly improbable single word removals, such as deletions of adverbs “never” or “nowhere”, which may turn a negative statement into a positive one.4 A second type of annotation that can be added to syntactic categories is the so-called parent annotation (Johnson, 1998), which was effectively used in syntactic parsing to break unreasonable context-free assumptions.
J98-4004
In this paper, we present a head-driven Markovization of SCFG compression rules, an approach that was successfully used in syntactic parsing (Collins, 1999; Klein and Manning, 2003) to alleviate issues intrinsic to relative frequency estimation of treebank productions.
P03-1054
