This phenomenon is also known as the DOP hypothesis (Bod 1998), and has been confirmed for Tree-DOP on the ATIS, OVIS and Wall Street Journal treebanks (see Bod 1993, 1998, 1999, 2000a; Sima'an 1999; Bonnema et al.1997; Hoogweg 2000).
C00-1010 C00-1011 P97-1021 P98-1022
Most probability models for DOP use the relative frequency estimator to estimate fragment probabilities, although Bod (2000b) trains fragment probabilities by a maximum likelihood reestimation procedure belonging to the class of expectation-maximization algorithms.
C00-1010 C00-1011
Bonnema et al.1997; Bod 2000a).
C00-1010 C00-1011 P97-1021
This paper presents ongoing work on DOP models for Lexical-Functional Grammar representations, known as LFG-DOP (Bod & Kaplan 1998).
P98-1022
R. Bod, 2000a.
C00-1010 C00-1011
R. Bod, 1998.
P98-1022
Black et al., 1991.
H91-1060
of LFG-DOP In accordance with Bod (1998), a particular DOP model is described by • a definition of a well-formed representation for utterance analyses, • a set of decomposition operations that divide a given utterance analysis into a set of fragments, • a set of composition operations by which such fragments may be recombined to derive an analysis of a new utterance, and • a definition of a probability model that indicates how the probability of a new utterance analysis is computed.
P98-1022
R. Bod, 2000d.
C00-1010 C00-1011
To give a precise definition of LFG-DOP fragments, it is convenient to recall the decomposition operations employed by the orginal DOP model which is also known as the "Tree-DOP" model (Bod 1993, 1998): (1) Root: the Root operation selects any node of a tree to be the root of the new subtree and erases all nodes except the selected node and the nodes it dominates.
P98-1022
R. Bod 2000c.
C00-1010 C00-1011
As a stop condition on the number of sampled derivations, we compute the probability of error, which is the probability that the analysis that is most frequently generated by the sampled derivations is not equal to the most probable analysis, and which is set to 0.05 (see Bod 1998).
P98-1022
This result is promising since TreeDOP has been shown to obtain state-of-the-art performance on the Wall Street Journal corpus (see Bod 2000a).
C00-1010 C00-1011
with LFG-DOP In his PhD-thesis, Cormons (1999) presents a parsing algorithm for LFG-DOP which is based on the Tree-DOP parsing technique described in Bod (1998).
P98-1022
DOP models have been shown to achieve state-of-the-art parsing performance on benchmarks such as the Wall Street Journal corpus (see Bod 2000a).
C00-1010 C00-1011
For an illustration of the composition operation, see Bod & Kaplan (1998).
P98-1022
Besides an exact match accuracy metric, we also used a more fine-grained score based on the well-known PARSEVAL metrics that evaluate phrase-structure trees (Black et al.1991). The PARSEVAL metrics compare a proposed parse P with the corresponding correct treebank parse T as follows: Precision = # correct constituents in P # constituents in P # correct constituents in P # constituents in T Recall = A constituent in P is correct if there exists a constituent in T of the same label that spans the same words and that φ-corresponds to the same f-structure unit (see Bod 2000c for some illustrations of these metrics for LFG-DOP).
C00-1010 C00-1011 H91-1060
The experiments show that the DOP hypothesis, which states that there is an increase in parse accuracy if larger fragments are taken into account (Bod 1998), is confirmed for LFG-DOP.
P98-1022
Bod 1993, 1998; Chappelier & Rajman 2000; Goodman 1998; Hoogweg 2000).
C00-1010 C00-1011 P98-1022
R. Bod 2000b.
C00-1010 C00-1011
According to Bod & Kaplan (1998), Discard-generated fragments are needed to parse sentences that are "ungrammatical with respect to the corpus", thus increasing the robustness of the model.
P98-1022
The DOP model has also been tested as a model for human sentence processing (Bod 2000d).
C00-1010 C00-1011
Tree-Insertion Grammar (Hoogweg 2000), Tree-Adjoining Grammar (Neumann 1998), Lexical-Functional Grammar (Bod & Kaplan 1998; Cormons 1999), Head-driven Phrase Structure Grammar (Neumann & Flickinger 1999), and Montague Grammar (Bonnema et al.1997; Bod 1999).
P97-1021 P98-1022
In defining a DOP model for LFG representations, Bod & Kaplan (1998) give the following settings for DOP's four parameters.
P98-1022
