The current paper uses a similar methodology for on-line problem detection as Walker et al.(2000b), but (1) we take a bottom-up approach, focussing on a small number of features and investigating their usefulness on a per-feature basis and (2) the features which we study are automatically available in the majority of current spoken dialogue system: the sequence of system question types and the word graphs corresponding to the respective user utterances.
A00-2028
For instance, Litman et al.(1999) and Walker et al.(2000a) use RIPPER (Cohen 1996) to classify problematic and unproblematic dialogues.
A00-2028 P99-1040
In sum, it is uncertain whether other spoken dialogue systems can benefit from the findings described by Walker et al.(2000b), since it is unclear which features are important and to what extent these features are available in other spoken dialogue systems.
A00-2028
Following up on this, Walker et al.(2000b) aim at detecting problems at the utterance level, based on data obtained with AT&Ts How May I Help You (HMIHY) system (Gorin et al.1997). Walker and co-workers apply RIPPER to 43 features which are automatically generated by three modules of the HMIHY system, namely the speech recognizer (ASR), the natural language understanding module (NLU) and the dialogue manager (DM).
A00-2028
Walker et al.(2000b) also briefly compare the performance of RIPPER with some other machine learning approaches, and show that it performs comparable to a memory-based (instance-based) learning algorithm (IB, see Aha et al.1991). The results which Walker and co-workers describe show that it is possible to automatically detect communication problems in the HMIHY system, using machine learning techniques.
A00-2028
