The language (set of analyses)6 generated by an OT system is defined as a106 a24 a94 a25 a13a108a107 a31a110a109a112a111a55a78a88a113a95a111a114a32 a10a27a81 a62a64a70a65a82a62a83a66a68a67 a115a80a116 a113 a62a64a118a117 a31a110a109 a111 a78a119a113 a111 a32 a10 Evala120a122a121a55a123a124a19a125a127a126 a24 Gen a128a72a129a130a2a131a58a129a132a58a133 a24 a113 a62a64 a25a80a25a88a134 4 LFG generation Our decidability proof for generation-based optimization builds on the result of (Kaplan and Wedekind, 2000) (K&W00) that LFG generation produces context-free languages.
C00-1062
For computational OT syntax, an interleaving of candidate generation and constraint checking has been proposed (Kuhn, 2000).
P00-1046
The comparison-based setup of OT learning is closely related to discriminative learning approaches in probabilistic parsing (Johnson et al., 1999; Riezler et al., 2000; Riezler et al., 2002),1 however the comparison of generation alternatives rather than parsing alternatives adds the possibility of systematically learning the basic language-specific grammatical principles (which in probabilistic parsing are typically fixed a priori, using either a treebankderived or a manually written grammar for the given a14 This work was supported by a postdoctoral fellowship of the German Academic Exchange Service (DAAD).
P00-1061 P02-1035 P99-1069
The proof builds on Kaplan and Wedekind’s (2000) construction showing that LFG generation produces contextfree languages.
C00-1062
(Kuhn, 2000) excludes the application of such recursions by a similar condition as offline parsability (which excludes vacuous recursions over a string in parsing), but with the a1a3a2 construction, this condition is not necessary for decidability of the generation-based optimization task.
P00-1046
3 OT-LFG Following (Bresnan, 2000; Kuhn, 2000; Kuhn, 2001), we define a restricted OT system based on Lexical-Functional Grammar (LFG) representations: c(ategory) structure/f(unctional) structure 2Most computational OT work so far focuses on candidates and constraints expressible as regular languages/rational relations, based on (Frank and Satta, 1998) (e.g., (Eisner, 1997; Karttunen, 1998; Gerdemann and van Noord, 2000)).
J98-2006 P00-1046 P97-1040 W98-1301
