Semantic Inclusion Weeds et al.(2004) attempted to refine the distributional similarity goal to predict whether one term is a generalization/specification of the other.
C04-1146
Concrete similarity measures compare a pair of weighted context feature vectors that characterize two words (Church and Hanks, 1990; Ruge, 1992; Pereira et al., 1993; Grefenstette, 1994; Lee, 1997; Lin, 1998; Pantel and Lin, 2002; Weeds and Weir, 2003).
J90-1003 P93-1024 W03-1011
Each feature represents another word (or term) with which w cooccurs, and possibly specifies also the syntactic relation between the two words as in (Grefenstette, 1994; Lin, 1998; Weeds and Weir, 2003).
W03-1011
The most widely used association weight function is (point-wise) Mutual Information (MI) (Church and Hanks, 1990; Lin, 1998; Dagan, 2000; Weeds et al., 2004).
C04-1146 J90-1003
Different metrics have been used, such as weighted Jaccard (Grefenstette, 1994; Dagan, 2000), cosine (Ruge, 1992), various information theoretic measures (Lee, 1997), and the widely cited and competitive (see (Weeds and Weir, 2003)) measure of Lin (1998) for similarity between two words, w and v, defined as follows:, ),(),( ),(),( ),( )()( )()(    ∈∈ ∩∈ + + = fvweightfwweight fvweightfwweight vwsim vFfwFf vFwFf Lin where F(w) and F(v) are the active features of the two words (positive feature weight) and the weight function is defined as MI.
W03-1011
Most works that attempt to learn such concrete lexical semantic relations employ a co-occurrence pattern-based approach (Hearst, 1992; Ravichandran and Hovy, 2002; Moldovan et al., 2004).
C92-2082 P02-1006 W04-2609
A few recent works (Ravichandran and Hovy, 2002; Keller et al., 2002; Chklovski and Pantel, 2004) used the web to collect statistics on word cooccurrences.
P02-1006 W02-1030 W04-3205
Throughout this paper we used syntactic features generated by the Minipar dependency parser (Lin, 1993).
P93-1016
