Lexical Weighting Previous research has shown that weighting schemes play an important role in segmentation performance (Ji and Zha, 2003; Choi et al., 2001).
W01-0514
Cosine similarity is commonly used in text segmentation (Hearst, 1994).
P94-1002
We test the system on a range of data sets, including the Physics and AI lectures and the synthetic corpus created by Choi (2000).
A00-2004
Synthetic Corpus Also as part of our analysis, we used the synthetic corpus created by Choi (2000) which is commonly used in the evaluation of segmentation algorithms.
A00-2004
Previous research has analyzed various facets of lexical distribution, including lexical weighting, similarity computation, and smoothing (Hearst, 1994; Utiyama and Isahara, 2001; Choi, 2000; Reynar, 1998; Kehagias et al., 2003; Ji and Zha, 2003).
A00-2004 E03-1058 P01-1064 P94-1002
This is evident in the performance of existing unsupervised algorithms on less structured datasets, such as spoken meeting transcripts (Galley et al., 2003).
P03-1071
We follow Choi (2000) and compute the mean segment length used in determining the parameter k on each reference text separately.
A00-2004
Church. 1993.
P93-1001
Metric We use the Pk and WindowDiff measures to evaluate our system (Beeferman et al., 1999; Pevzner and Hearst, 2002).
J02-1002
Following the first unsupervised segmentation approach by Hearst (1994), most algorithms assume that variations in lexical distribution indicate topic changes.
P94-1002
We use the text Dotplotting representation by (Church, 1993) and plot the cosine similarity scores between every pair of sentences in the text.
P93-1001
Comparison with local dependency models We compare our system with the state-of-the-art similarity-based segmentation system developed by Choi (2000).
A00-2004
For example, most algorithms achieve high performance on synthetic collections, generated by concatenation of random text blocks (Choi, 2000).
A00-2004
Segmentation Study Spoken lectures are very different in style from other corpora used in human segmentation studies (Hearst, 1994; Galley et al., 2003).
P03-1071 P94-1002
This algorithm (Utiyama and Isahara, 2001) (UI) computes the optimal segmentation by estimating changes in the language model predictions over different partitions.
P01-1064
This issue has been explored in the past (Ji and Zha, 2003; Utiyama and Isahara, 2001), and we will explore the existing strategies in our framework.
P01-1064
We use the publicly available implementation of the system and optimize the system on a range of mask-sizes and different parameter settings described in (Choi, 2000) on a heldout development set of three lectures.
A00-2004
