Such charts can be computed efficiently (Koller and Thater, 2005b) from a dominance graph, and can also be used to compute the configurations of a graph efficiently.
P05-3003
Fuchss et al.(2004) have presented a corpus study that strongly suggests that all dominance graphs that are generated by current largescale grammars are (or should be) hnc.
P04-1032
Rather, we will use dominance charts (Koller and Thater, 2005b) as our USRs: they are more explicit USRs, which support a more finegrained deletion of reading sets than graphs.
P05-3003
Hnc graphs are equivalent to chain-connected dominance constraints (Koller et al., 2003), and areclosely relatedto dominance nets (Niehrenand Thater, 2003).
E03-1024 P03-1047
It is an improvement over earlier algorithms for enumerating irredundant readings (Vestre, 1991; Chaves, 2003) in that it maintains underspecifiedness; note that these earlier papersnevermadeanyclaimswithrespectto,orevaluated, completeness.
E91-1044
Resources. The experiments are based on the Rondane corpus, a Redwoods (Oepen et al., 2002) style corpus which is distributed with the English Resource Grammar (Flickinger, 2002).
C02-2025
The particular USRs we workwithareunderspecifiedchartrepresentations, which can be computed from dominance graphs (or USRs in some other underspecification formalisms) efficiently (Koller and Thater, 2005b).
P05-3003
There has been previous research on enumerating only some representatives of each equivalence class (Vestre, 1991; Chaves, 2003), but these approaches don’t maintain underspecification: After running their algorithms, they are left with a set of readings rather than an underspecified representation, i.e. we could no longer run other algorithms on an USR.
E91-1044
The MRS representations are translated into dominance graphs using the open-source utool tool (Koller and Thater, 2005a), which is restricted to MRS representations whose translations are hnc.
P05-3003
and are small in practice (see (Koller and Thater, 2005b) for an analysis).
P05-3003
This simplifies semantics construction, and current algorithms support the efficient enumeration of the individual semantic representations from an USR (Koller and Thater, 2005b).
P05-3003
