These transducers are inferred using the GIATI technique (Casacuberta and Vidal, 2004).
J04-2004
• Key-Stroke Ratio (KSR): Number of keystrokes that are necessary to achieve the reference translation divided by the number of running characters (Och et al., 2003) 1.
J03-1002
These alignments can be obtained from single-word models (Brown et al., 1993) using the available public software GIZA++ (Och and Ney, 2003).
J03-1002 J93-2003
In (Och et al., 2003) the Alignment-Templates translation model is used.
J03-1002
A desirable feature of the iterative machine translation system is the possibility of producing a list of target suffixes, instead of only one (Civera et al., 2004).
W04-3245
The second one is heuristic and tries to use a wordaligned corpus (Zens et al., 2002; Koehn et al., 2003).
E03-1032 N03-1017
In the PB approach monotone search is more efficient than non-monotone search and obtains similar translation results for the tasks described in this article (Tom´as and Casacuberta, 2004).
J04-2004
Models of this kind assume that an input word is generated by only one output word (Brown et al., 1993).
J93-2003
work Several CAT systems have been proposed in the TransType projects (SchlumbergerSema S.A. et al., 2001): In (Foster et al., 2002) a maximum entropy version of IBM2 model is used as translation model.
W02-1020
• Character Error Rate (CER): Edit distance in terms of characters between the target sentence provided by the system and the reference translation (Civera et al., 2004).
W04-3245
This method can reduce the generation capability of the fully fledged translation model (Och et al., 2003; Bender et al., 2005).
J03-1002
A simple alternative to these models has been proposed, the phrase-based (PB) approach (Tom´as and Casacuberta, 2001; Marcu and Wong, 2002; Zens et al., 2002).
W02-1018
In (Civera et al., 2004) finite state transducers are presented as a candidate technology in the CAT paradigm.
W04-3245
Statistical machine translation (SMT) is an adequate framework for CAT since the MT models used can be learnt automatically from a training bilingual corpus and the search procedures developed for SMT can be adapted efficiently to this new interactive framework (Och et al., 2003).
J03-1002
This work follows the approach of interactive CAT initially suggested by (Foster et al., 1996) and developed in the TransType2 project (SchlumbergerSema S.A. et al., 2001; Barrachina et al., 2006).
C96-1067
The methodology used (Brown et al., 1993) is based on the definition of a function Pr(tI1|sJ1) that returns the probability that tI1 is a 835 source Transferir documentos explorados a otro directorio interaction-0 Move documents scanned to other directory interaction-1 Move s canned documents to other directory interaction-2 Move scanned documents to a nother directory interaction-3 Move scanned documents to another f older acceptance Move scanned documents to another folder Figure 1: Example of CAT system interactions to translate the Spanish source sentence into English.
J93-2003
For the distortion model, it is also assumed that an alignment depends only on the distance of the two phrases (Och and Ney, 2000): p(αk|αk−1) = p|γαk−γαk−1|0. (5) There are different approaches to the parameter estimation.
P00-1056
• Word Error Rate (WER): Edit distance in terms of words between the target sentence provided by the system and the reference translation (Och and Ney, 2003).
J03-1002
Casacuberta. 2004.
J04-2004
The first one corresponds to a direct learning of the parameters of equations 3 or 4 from a sentence-aligned corpus using a maximum likelihood approach (Tom´as and Casacuberta, 2001; Marcu and Wong, 2002).
W02-1018
