Och. 2003.
P03-1021
For MT, MBR decoding was introduced in (Kumar and Byrne, 2004).
N04-1022
Score The BLEU score (Papineni et al., 2002) measures the agreement between a hypothesiseI1 generated by the MT system and a reference translation ˆeˆI1.
P02-1040
In the following, we will call this decision rule the MBR rule (Kumar and Byrne, 2004).
N04-1022
The model scaling factors λM1 are optimized with respect to the BLEU score as described in (Och, 2003).
P03-1021
System The posterior probability Pr(eI1|fJ1 ) is modeled directly using a log-linear combination of several models (Och and Ney, 2002): Pr(eI1|fJ1 ) = exp parenleftBigsummationtextM m=1 λmhm(e I1,fJ1 ) parenrightBig summationtext Iprime,eprimeIprime1 exp parenleftBigsummationtextM m=1 λmhm(eprime Iprime1,fJ 1 ) parenrightBig (1) This approach is a generalization of the sourcechannel approach (Brown et al., 1990).
J90-2002 P02-1038
