Authorability is stressed in IDAS because we believe this is the best way to achieve IDAS'S goal of fairly broad, but not necessarily deep, domain coverage; short responses are stressed because IDAS's hypertext interface should allow users to dynamically choose the paragraphs they wish to read, i.e., perform their own highlevel text-planning \[Reiter et al., 1992\].
A92-1009 C92-1038
If a unification system is based on a typed feature logic, then its grammar can include classificationlike subsumption tests \[Elhadad, 1990\], and thus be as expressive in specifying patterns as a classification system.
P90-1020
• Text Planning: An expression in the ISI Sentence Planning Language (SPL) \[Kasper, 1989\] is formed from the information specified in the content-determination rule.
H89-1022
\[Moore and Paris, 1989\] Johanna Moore and Cecile Paris.
P89-1025
\[Reiter et al., 1992\] Ehud Reiter, Chris Mellish, and John Levine.
A92-1009 C92-1038
\[Kasper, 1989\] Robert Kasper.
H89-1022
\[Elhadad, 1990\] Michael Elhadad.
P90-1020
\[Wahlster et al., 1991; Moore and Paris, 1989\]).
P89-1025
More sophisticated text-structuring techniques have been discussed by, among others, Mann and Moore \[1981\], who used a hill-climbing algorithm based on an explicit preference function.
J81-1002
The logic underlying FUG is relatively simple, but much more expressive logics are now being implemented \[Emele and Zajac, 1990; D6rre and Seiffert, 1991; D/Srre and Eisele, 1991\].
C90-3052
\[Evans and Gazdar, 1989\] Roger Evans and Gerald Gazdar.
E89-1009
\[Reiter and Dale, 1992\] Ehud Reiter and Robert Dale.
A92-1009 C92-1038
Systemic systems vary substantially in the input language they accept; we will here focus on the NIGEL system \[Mann, 1983\], since it uses the same input language (SPL) as IDAS'S surface realisation system, s Other systemic systems (e.g., \[Patten, 1988\]) tend to use systemic features as their input language (i.e., they don't have an equivalent of NIGEL'S chooser mechanism), which makes comparisons more difficult.
P83-1012
\[Mann and Moore, 1981\] William Mann and James Moore.
J81-1002
Classification and inheritance are used in this manner by the IDAS natural language generation system \[Reiter et al., 1992\], and their use has allowed IDAS to use a single knowledge representation system for both linguistic and domain knowledge.
A92-1009 C92-1038
\[Emele and Zajac, 1990\] Martin Emele and R~mi Zajac.
C90-3052
\[Mann, 1983\] William Mann.
P83-1012
DATR \[Evans and Gazdar, 1989\] is a system that declaratively represents morphological rules, using a representation that in some ways is similar to I1.
E89-1009
Referring expressions in IDAS are generated by the algorithm described in \[Reiter and Dale, 1992\].
A92-1009 C92-1038
