A number of equivalence relations between the classes of yield languages generated by fts' and other computational models have been established (Engelfriet 1991)(Engelfriet 1980)(Weir 1992).
P92-1018
Weir, D.J. 1992.
P92-1018
An equivalence relation *1 is shown in (Weir 1992).
P92-1018
We also note that all the inclusion relations are proper; indeed, 0 l {ala2a3a41n >_ E D E a a2 n n _ ..... a2m_la2m \[ n > E C D for m > 3, (by (Vijay-Shanker 1987)).
P87-1015
Especially, it has been shown that the class of yield languages generated by finite-copying fts' equals to the class of languages generated by lcfrs' (Weir 1992), hence by mcfg's.
P92-1018
A number of grammatical formalisms such as lexical-functional grammars (Kaplan 1982), head grammars (Pollard 1984) and tree adjoining grammars (Joshi 1975)(Vijay-Shanker 1987) were introduced to define the syntax of natural languages.
P87-1015
Vijay-Shanker, K., Weir, D.J. and Joshi, A.K. 1987.
P87-1015
