of Functional Centering Within the framework of the centering model (Grosz et al., 1995), we distinguish each utterance's backward-looking center (Gb(U,~)) and its forwardlooking centers (G!
J95-2003
In the third column of Table 8 we give the numbers of transitions which are generated by the canonical constraints as stated by Grosz et al.(1995, p.214, 217).
J95-2003
Only few of these cross-linguistic studies have led to changes in the basic order of discourse entities, the work of Walker et al.(1990; 1994) being the most far reaching exception.
J94-2003
~Table 1 contains the most explicit ordering of grammatical roles we are aware of and has been taken from Brennan et al.(1987). Often, the distinction between complements and adjuncts is collapsed into the category "others" (c.f., e.g., Grosz et al.(1995)). Our work on the resolution of anaphora (Strube & Hahn, 1995; Hahn & Strube, 1996) and textual ellipsis (Hahn et al., 1996), however, is based on German, a free word order language, in which grammatical role information is far less predictive for the organization of centers.
C96-1084 E95-1033 J95-2003 P87-1022 P96-1057
the enumeration in Grosz et al.(1995)), an almost canonical scheme for the ordering on the forward-looking centers has emerged, one that reflects well-known regularities of fixed word order languages such as English.
J95-2003
While it is usually assumed that the elliptical expression ranks above its antecedent (Grosz et al., 1995, p.217), we assume the contrary.
J95-2003
In particular, chains of the RETAIN transition in passages where the Cb does not change (passages with constant theme) show that the canonical ordering constraints for the forwardlooking centers are not appropriate, The numbers of centering transition pairs generated by the different approaches are shown in Table 10, In general, the functional approach shows the best re6As a consequence of this postulate, we have to redefine Rule 2 of the Centering Constraints (Grosz et al., 1995, p.215) appropriately, which gives an informal characterization of a preference for sequences of CONTINUE over sequences of RETAIN arid, similarly, sequences of RETAIN over sequences of SHIFT.
J95-2003
Strube (1996)).
P96-1057
Brennan et al.(1987, p.157)) our constraints fail to properly rank the elements of the third sentence C! of that example.
P87-1022
also that these results were achieved without having recourse to extra constraints, e.g., the shared property constraint to account for anaphora parallelism (Kameyama, 1986).
P86-1031
The ordering constraints we supply account for all of the above mentioned types of anaphora in a precise way, including (pro)nominal anaphora (Strube & Hahn, 1995; Hahn & Strube, 1996).
C96-1084 E95-1033 P96-1057
We use an approach as described by Strube (1996) for the evaluation.
P96-1057
example (30) of Walker et al.(1994, p.214) causes the same problems they described (discourse-initial utterance, semantic or world knowledge should be available).
J94-2003
Strube (1996).
P96-1057
Even for the crucial examples (32)-(36) of Walker et al.(1994, p.216-221) our constraints generate the same Cls as Walker et al'.
J94-2003
Hence, the most important single construct of the centering model is the ordering of the list of forward-looking centers (Walker et al., 1994).
J94-2003
Table 7) are taken from Walker et al.(1994). ~(~)= ~(~) ~(~)# ~(~) cb(u).
J94-2003
We, therefore, re-evaluated the examples already annotated with Gb/C! data available in the literature (for the English language, we considered all exampies from Grosz et al.(1995) and Brennan et al.(1987); for Japanese we took the data from Walker et al.(1994)). Surprisingly enough, all examples of Grosz et al.(1995) passed the test successfully.
J94-2003 J95-2003 P87-1022
Interestingly enough, several extra assumptions introduced to account, e.g., for anaphora parallelism (e.g., the shared property constraint formulated by Kameyama (1986)) can be eliminated without affecting the correctness of anaphora resolutions.
P86-1031
In particular, methods for the interaction between intraand intersentential anaphora resolution have to be defined, since the centering model is concerned only with the latter case (see Suri & McCoy (1994)).
J94-2006
57-63. SA performance evaluation of the current anaphora and ellipsis resolution capacities of our system is reported in Hahn et al.(1996). 273 constraint that elliptical antecedents are ranked higher than elliptical expressions (short: "ante > express").
C96-1084
The centering model has evolved as a methodology for the description and explanation of the local coherence of discourse (Grosz et al., 1983; 1995), with focus on pronominal and nominal anaphora.
J95-2003 P83-1007
But the items of the focus lists are either ordered by thematic roles (Sidner, 276 1983) or grammatical roles (Suri & McCoy, 1994; Dahl & Ball, 1990)).
J94-2006
the relation part-of between the concepts ACCUMULATOR and 316LT, is available (see Hahn et al.(1996) for a more detailed treatment of text ellipsis resolution).
C96-1084
275 CONTINUE cheap CONTINUE cheap RETAIN expensive SMOOTH-SHIFT cheap ROUGH-SHIFT expensive RETAIN expensive cheap expensive expensive expensive SMOOTH-SHIFT expensNe cheap expens~e cheap ROUGH-SHIFT i expensive expensive expensive expensive Table 9: Costs for Transition Pairs naive & cost type naive ante > express cheap 72 180 1T expensive 317 209 Cheap 25 36 Spiegel expensive 50 39 cheap 45 48 MOiler expensive 34 31 cheap 142 264 expensive 401 279 c~onical 129 260 45 30 46" 33,220 323 functional ante > express 236 153 51 24 48 31 335 208 321 68 62 13 55 24 438 105 Table 10: Cost Values for Centering Transition Pair Types verbs (Walker et al., 1994).
J94-2003
with Related Approaches The centering model (Grosz et al., 1983; 1995) is concerned with the interactions between the local coherence of discourse and the choices of referring expressions.
J95-2003 P83-1007
With the exception of Walker et al.(1990; 1994) for Japanese, Turan (1995) for Turkish, Rambow (1993) for German and Cote (1996) for English, only grammatical roles are considered and the (partial) ordering in Table 11 is taken for granted.
J94-2003
Clark (1975)).
T75-2034
As a consequence, we argue against Walker et al.'s (1994, p.227) stipulation, which assumes that the C I ranking is the only parameter of the centering theory which is language-dependent.
J94-2003
To summarize the results of our empirical evaluation, we first claim that our proposal based on functional criteria leads to substantially better and -with respect to the inference load placed on the text understander, whether human or machine -more plausible results for languages with free word order than the structural constraints given by Grosz et al.(1995) and those underlying a naive approach.
J95-2003
the examples given in the next section), in particular, is usually only sketchily dealt with in the centering literature, e.g., by asserting that the entity in question "is realized but not directly realized" (Grosz et al., 1995, p.217).
J95-2003
