with Grammar Induced by Pereira and Schabes Method The experiment of Pereira and Schabes (1992) was duplicated.
P92-1017
That is, most parsing algorithms assume that the test corpus was generated by the model, and then attempt to evaluate the following expression, where E denotes the expected value operator: Ta = argmTaXE ( 1 ifL = gc) (1) This is true of the Labelled Tree Algorithm and stochastic versions of Earley's Algorithm (Stolcke, 1993), and variations such as those used in Picky parsing (Magerman and Weir, 1992).
P92-1006
We have used the technique outlined in this paper in other work (Goodman, 1996) to efficiently parse the DOP model; in that model, the only previously known algorithm which summed over all the 182 Criterion Label I Label Brack Cons Brack Cons Brack Algorithm Tree \] Recall Recall Recall Tree Label Tree 4.54~ 48.60% 60.98% 66.35% 12.07% Label Recall 3.71% 49.66~ 61.34% 68.39% 11.63% Bracket Recall 0.11% 4.51% 61.63~ 68.17% 11.19% Table 2: Grammar Induced by Counting: Three Algorithms Evaluated on Five Criteria possible derivations was a slow Monte Carlo algorithm (Bod, 1993).
E93-1006 W96-0214
Similarly, some grammar induction algorithms, such as those used by Pereira and Schabes (1992) do not produce meaningful labels.
P92-1017
