In earlier IBM translation systems (Brown et al., 1993) each English word would be generated by, or "aligned to", exactly one formal language word.
J93-2003
Model 1 is the word-pair translation model used in simple machine translation and understanding models (Brown et al., 1993; Epstein et al., 1996).
J93-2003
More recently, BBN has replaced handwritten rules with decision trees (Miller et al., 1996).
P96-1008
ibm. com Abstract Several recent efforts in statistical natural language understanding (NLU) have focused on generating clumps of English words from semantic meaning concepts (Miller et al., 1995; Levin and Pieraccini, 1995; Epstein et al., 1996; Epstein, 1996).
P96-1008
Two more powerful modeling techniques for modeling clump generation are n-gram language models (Miller et al., 1995; Levin and Pieraccini, 1995; Epstein, 1996), and headword language models (Epstein, 1996).
P96-1008
This paper extends the IBM Machine Translation Group's concept of fertility (Brown et al., 1993) to the generation of clumps for natural language understanding.
J93-2003
For the ATIS task, our formal language is a minor variant of the NL-Parse (Hemphill, Godfrey, and Doddington, 1990) used by ARPA to annotate the ATIS corpus.
H90-1021
