The tra985 ditional alignment probabilities depend on absolute positions and do not take that into account, as has already been noted by (Vogel et al., 1996).
C96-2141
The application of this algorithm to the basic problem using a parallel bilingual corpus aligned on the sentence level is described in (Brown et al., 1993).
J93-2003
In the refined model 2 (Brown et al., 1993) alignment probabilities a(ilj, l, m) are included to model the effect that the position of a word influences the position of its translation.
J93-2003
The simple model 1 (Brown et al., 1993) for the translation of a SL sentence d = dl...dt in a TL sentence e = el... em assumes that every TL word is generated independently as a mixture of the SL words: m l P(e\[d),,~ H ~ t(ej\[di) (2) j=l i=O In the equation above t(ej\[di) stands for the probability that ej is generated by di.
J93-2003
