Diagrams may be easier to understand than logical formalisms, but they still lack the flexibility and familiarity of natural language text, as empirical studies on editing diagrammatic representations have shown (Kim, 1990; Petre, 1995); for discussion see Power et al.(1998). This observation has led us to explore a new possibility, at first sight paradoxical: that of a symbolic authoring system in which the current knowledge base is presented through a natural language text generated by the system.
W98-1437
Feedback texts with menus have been used before in the NL-Menu system (Tennant et al., 1983), but only as a means of presenting syntactic options.
P83-1023
A more detailed description of the architecture is given in Scott et al.(1998). 2 Example of a WYSIWYM system The first application of WYSIWYM was DRAFTER-II, a system which generates in1054 stuctions for using word processors and diary managers.
W98-1427
Owing to this cost, M-NLG has been applied mainly in contexts where the knowledge base is already available, having been created for another purpose (Iordanskaja et al., 1992; Goldberg et al., 1994); for discussion see Reiter and Mellish (1993).
C92-3158
