Busemann and Horacek (1998) describe a system that mixes templates and rulebased generation.
W98-1425
In Busemann and Horacek (1998), the remaining output is generated by grammar rules.
W98-1425
Surface Realization We follow Busemann and Horacek (1998) in designing our generation engine with "different levels of granularity".
W98-1425
However, there is still the burden of writing and maintaining grammar rules, and processing time is probably too slow for sentences using grammar rules (only the average time for templates and rule-based sentences combined is reported in Busemann and Horacek, 1998), for use in spoken dialogue systems.
W98-1425
