(Elzer, Chu-Carroli et al.1994; Chu-Carroll and Carberry 1998) studied the generation of evaluative arguments in the context of collaborative planning dialogues.
J98-3002
We have applied our strategy in a system that serves as a realestate personal assistant (Carenini 2000a).
W00-1402
Elzer,.S.,..I_Giatt.-.Carrolk..et.al.(.1994).Recogn&ing environment to verify whether arguments generated by our strategy actually affect user attitudes in the intended direction (Carenini 2000b).
W00-1402
For sample arguments generated by our strategy see (Carenini 2000b) in this proceedings.
W00-1402
