Aggregation is performed according to heuristics similar to the ones proposed in (Shaw 1998).
W98-1415
A set of plan operators, implementing guidelines for content selection and organ(sat(on from argumentation theory (Carenini and Moore 2000).
W00-1407
(Chu-Carroll and Carberry 1998) tbr an illustration of how the specification of the context can become extremely complex when human judges are used to evaluate content selection strategies for a dialog system.
J98-3002
We are currently applying the framework to evaluate arguments generated by an argument generator we have developed (Carenini 2000).
W00-1407
The human judges evaluation method requires a panel of judges to score outputs of generation models (Chu-Carroll and Carberry 1998; Lester and Porter March 1997).
J97-1004 J98-3002
As the field of NLG matures, we are witnessing a growing interest in studying empirical methods to evaluate computational models of discourse generation (Dale, Eugenio et al.1998). However, with the exception of (Chu-Carroll and Carberry 1998), little attention as been paid to the evaluation of systems generating evaluative arguments, communicative acts that attempt to affect the addressee's attitudes (i.e.
J98-3002
