McKeown K, Kukich K, Shaw J (1994).
A94-1002
In recent years many new content determination strategies have been proposed, ranging from the use of sophisticated signal-processing techniques (Boyd 1997) to complex planning algorithms (Mittal et al 1998) to systems which exploit cognitive models of the user (Fiedler 1998).
J98-3004 W98-1410
Human experts are often consulted with regard to the details of content rules, especially when schemas are used for content determination (Goldberg et al 1994, McKeown et al 1994, Reiter et al 2000); but they rarely seem to be consulted (as far as we can tell) when deciding on the general algorithm or strategy to use for content determination.
A94-1002 W00-1429
Mittal V, Moore J, Carenini G, and Roth S (1998).
J98-3004
from Other Projects After making the above observations, we examined think-aloud transcripts from an earlier project at the University of Aberdeen, STOP (Reiter et al 2000), which involved building an NLG system that produced smoking-cessation letters from smoking questionnaires.
W00-1429
In Reiter and Dale's (2000) terminology, overviews are a technique for generating Computable Data content, that is content which is not directly present in the input data but can be computed or inferred from it.
W00-1429
This model is based on extensive knowledge acquisition (KA) activies that we have carried out in the SUMTIME project (Sripada, 2001), and also matches observations made during KA activities carried out in the STOP project (Reiter et al 2000).
W00-1429
Barzilay R, McCullough D, Rambow O, DeChristofaro J, Korelsky T, and Lavoie B (1998) A New Approach to Expert System Explanations, In Proceedings of INLG-1998, pages 78-87.
W98-1409
Our model has some similarities to the one proposed by Barzilay et al (1998), in that the Domain Reasoner uses general domain knowledge similar to their RDK, while the Communication Reasoner uses communication knowledge similar to their CDK and DCK.
W98-1409
Content determination as the name indicates is the process responsible for determining the content of the texts generated by an NLG system (Reiter and Dale 2000).
W00-1429
Fiedler A (1998).
W98-1410
In the three-stage pipeline model of Reiter and Dale (2000), content determination is part of the first stage, document planning, along with document structuring (determining the textual and rhetorical structure of a text).
W00-1429
