This technique, however, does not split input into units globally, or sometimes does not output any translation result (Furuse et al, 1998).
P98-1070
The target language is generated by the combination of template method and generation technology (Wu, 2000).
C00-2174
Wakita et al.(1997) proposed a robust translation method which locally extracts only reliable parts, i.e., those within the semantic distance threshold and over some word length.
W97-0404
