The fact that the error rate more than doubles when the seeds in Yarowsky's (1995) experiments are reduced from a sense's best collocations to just one word per sense suggests that the error rate would increase further if no seeds were provided.
P95-1026
10Following Collins et al. (1999), we used a coarsened ver-
W99-0613
Michael Collins. 1999. Head-Driven Statistical Models for Natural Language Parsing. Ph.D. thesis, University of Pennsylvania.
W99-0613
M. Collins, J. Hajic, L. Ramshaw, and C. Tillmann. 1999 A Statistical Parser for Czech. In Proceedings of ACL pages 505512.
W99-0613
parser, the Collins (1999) parser, ported to Chinese.
W99-0613
Collins parser for Chinese The Collins parser is a state-of-the-art statistical parser that has high performance on English (Collins, 1999) and Czech(Collins et al.1999). There have been attempts in applying other algorithms in Chinese parsing (Bikel and Chiang, 2000; Chiang and Bikel 2002; Levy and Manning 2003), but there has been no report on applying the Collins parser on Chinese.
W99-0613
generated by the parsers of Collins (1999) and Char-
W99-0613
We then describe our port of the Collins (1999) parser to Chinese.
W99-0613
In recent years, many accurate phrase-structure parsers have been developed (e.g., (Collins, 1999; Charniak, 2000)).
W99-0613
The average performance of the SVD-based representations of 83% to 91% is satisfactory, although inferior by about 5% to 10%, to disambiguation with minimal manual intervention (e.g., Yarowsky \[1995\]).
P95-1026
Many of these features required creating an automatic parse; in doing so we showed that the Collins (1999) parser when ported to Chinese achieved the best reported performance on Chinese syntactic parsing.
W99-0613
on measures for inter-rater reliability (Carletta, 1996), on frameworks for evaluating spoken dialogue agents (Walker et al., 1998) and on the use of different corpora in the development of a particular system (The Carnegie-Mellon Communicator, Eskenazi et al.(1999)). The question we are addressing in this paper is how to collect and analyse relevant corpora.
J96-2004
Martinez, Eneko Agirre, One sense per collocation and genre/topic variations, Proceedings of the 2000 Joint SIGDAT conference on Empirical methods in natural language processing and very large corpora: held in conjunction with the 38th Annual Meeting of the Association for Computational Linguistics, p.207-215, October 07-08, 2000, Hong Kong 19 Hwee Tou Ng, Hian Beng Lee, Integrating multiple knowledge sources to disambiguate word sense: an exemplar-based approach, Proceedings of the 34th annual meeting on Association for Computational Linguistics, p.40-47, June 24-27, 1996, Santa Cruz, California 20 Geoffrey Nunberg.
W00-1326
Yarowsky (1995), Collins and Singer (1999), Riloff and Jones (1999)).
P95-1026 W99-0613
Yarowsky has proposed an algorithm that requires as little user input as one seed word per sense to start the training process (Yarowsky 1995).
P95-1026
