(Prolo, 2002) started from 57 elementary trees and 21 handcrafted MetaRules, and re-generated the verb trees of the hand-crafted Xtag grammar for English described in the previous section.
C02-1153
Kinyon. 2000.
C00-1065
Some trees generated by (Prolo, 2002) were not in the hand-crafted grammar (e.g.
C02-1153
a high level of syntactic abstraction) may be found in (Kinyon and Prolo, 2002).
C02-1153
Prolo. 2002.
C02-1153
For instance, (Doran et al., 1994) report that 61% of 1367 grammatical sentences from the TSNLP test-suite (Lehman and al, 1996) were parsed with an early version of the grammar.
C94-2149
Another possible approach for compact and abstract grammar encoding is the MetaGrammar (MG), initially developed by (Candito, 1996).
C96-1034
A TAG grammar may be viewed as consisting of two components: on the one 5Some extraction algorithms such as those of (Chen, 2001) or (Chiang, 2000) do retrieve the right the right domain of locality for this specific example, but do extract a domain of locality which is incorrect in some other cases.
P00-1058
For instance (Chiang, 2000), (Xia, 2001) (Chen, 2001) all automatically acquire large TAGs for English from the Penn Treebank (Marcus et al., 1993).
J93-2004 P00-1058
This amounts to extracting ”hypertags” (Kinyon, 2000) from the treebank, transforming these Hypertags into a MetaGrammar, and automatically generating a TAG from the MG.
C00-1065
it allows to add an argument for causatives, 9Due to space limitations, we refer to (Prolo, 2002) for a detailed discussion.
C02-1153
In the context of TAGs, one can cite the notion of MetaRules (Becker, 2000), (Prolo, 2002)8, and the notion of MetaGrammar (Candito, 1996), (Xia, 2001).
C02-1153 C96-1034
