10Following Collins et al. (1999), we used a coarsened ver-
W99-0613
generated by the parsers of Collins (1999) and Char-
W99-0613
In the following section, we propose an EM-style bootstrapping procedure (Cucerzan, 1999) for annotating the training data automatically.
W99-0612
Collins parser for Chinese The Collins parser is a state-of-the-art statistical parser that has high performance on English (Collins, 1999) and Czech(Collins et al.1999). There have been attempts in applying other algorithms in Chinese parsing (Bikel and Chiang, 2000; Chiang and Bikel 2002; Levy and Manning 2003), but there has been no report on applying the Collins parser on Chinese.
W99-0613
In addition to name probability, Chen (1998) also add extra scores to a name candidate according to context clues (such as position, title, speech-act verbs).
M98-1017
M. Collins, J. Hajic, L. Ramshaw, and C. Tillmann. 1999 A Statistical Parser for Czech. In Proceedings of ACL pages 505512.
W99-0613
66-73. Yu,S.,BaiS.andWuP.(1998)Description of the Kent Ridge Digital Labs System Used for MUC-7.
M98-1016
parser, the Collins (1999) parser, ported to Chinese.
W99-0613
methods that can be bootstrapped from a little seed data or a few seed rules (Collins, 1999; Cucerzan, 1999) are highly demanded to automatically annotate the training data.
W99-0612 W99-0613
Then, the most likely token sequence is selected according to a statistical model, such as Markov model (Bikel, 1997; Yu, 1998) or maximum entropy model (Borthwick, 1999).
A97-1029 M98-1016
There are two major approaches to NE recognition: the handcrafted approach (Grishman, 1995) and the statistical approach (Bikel, 1997; Chen, 1998; Yu, 1998).
A97-1029 M95-1014 M98-1016 M98-1017
Sproat (1994) proposed to recognize Chinese personal names with the stochastic finite-state word segmentation algorithm.
P94-1010
Michael Collins. 1999. Head-Driven Statistical Models for Natural Language Parsing. Ph.D. thesis, University of Pennsylvania.
W99-0613
Stanley F. Chen and Joshua Goodman. 1998. An Empir-
M98-1017
(Chen and Goodman, 1998). The Maximum Entro-
M98-1017
We then describe our port of the Collins (1999) parser to Chinese.
W99-0613
Many of these features required creating an automatic parse; in doing so we showed that the Collins (1999) parser when ported to Chinese achieved the best reported performance on Chinese syntactic parsing.
W99-0613
Yarowsky (1995), Collins and Singer (1999), Riloff and Jones (1999)).
W99-0613
In recent years, many accurate phrase-structure parsers have been developed (e.g., (Collins, 1999; Charniak, 2000)).
W99-0613
