10Following Collins et al. (1999), we used a coarsened ver-
W99-0613
Universidad 30 Legans 28911, Madrid, Spain pmf@inf.uc3m.es G47G88G76G86G3G53G82G71G85G76G74G82 ISYS Group AI Department Technical University of Madrid Boadilla del Monte, 28660 Madrid, Spain lrodrigo@isys.dia.fi.upm.es G36G69G86G87G85G68G70G87 This paper presents the adaptation and customization of two lexical resources: Brill tagger, Brill (1992), and EuroWordNet, Vossen et al.(1998), to be used in the ADVICE project devoted to build an intelligent virtual reality sales and service system that uses human language technology.
A92-1021
M. Collins, J. Hajic, L. Ramshaw, and C. Tillmann. 1999 A Statistical Parser for Czech. In Proceedings of ACL pages 505512.
W99-0613
G23G3 G36G71G68G83G87G76G81G74G3G37G85G76G79G79G3G55G68G74G74G72G85 The Brill tagger, Brill (1992), is a rule-based part of speech tagger programmed in Perl for English language.
A92-1021
Evaluation The SNC-Value method wan initially t(;sted on a eorl)US of 800,000 eye t)athoh)gy reI)ortn, which had 1)een tagged with the Brill t)art-of-nl)eeeh tagger (Brill, 1992).
A92-1021
This has been carried out considering the information in Brill (1992), Brill (1994) and Brill (1995), taken as a reference starting point.
A92-1021 J95-4004
parser, the Collins (1999) parser, ported to Chinese.
W99-0613
Collins parser for Chinese The Collins parser is a state-of-the-art statistical parser that has high performance on English (Collins, 1999) and Czech(Collins et al.1999). There have been attempts in applying other algorithms in Chinese parsing (Bikel and Chiang, 2000; Chiang and Bikel 2002; Levy and Manning 2003), but there has been no report on applying the Collins parser on Chinese.
W99-0613
Then, the most likely token sequence is selected according to a statistical model, such as Markov model (Bikel, 1997; Yu, 1998) or maximum entropy model (Borthwick, 1999).
A97-1029
There are two major approaches to NE recognition: the handcrafted approach (Grishman, 1995) and the statistical approach (Bikel, 1997; Chen, 1998; Yu, 1998).
A97-1029
generated by the parsers of Collins (1999) and Char-
W99-0613
Following Pradhan et al.(2003), we used tinySVM along with YamCha (Kudo and Matsumoto 2000, 2001) as the SVM training and test software.
W00-0730
Michael Collins. 1999. Head-Driven Statistical Models for Natural Language Parsing. Ph.D. thesis, University of Pennsylvania.
W99-0613
In recent years, many accurate phrase-structure parsers have been developed (e.g., (Collins, 1999; Charniak, 2000)).
W99-0613
We then describe our port of the Collins (1999) parser to Chinese.
W99-0613
Many of these features required creating an automatic parse; in doing so we showed that the Collins (1999) parser when ported to Chinese achieved the best reported performance on Chinese syntactic parsing.
W99-0613
methods that can be bootstrapped from a little seed data or a few seed rules (Collins, 1999; Cucerzan, 1999) are highly demanded to automatically annotate the training data.
W99-0613
Yarowsky (1995), Collins and Singer (1999), Riloff and Jones (1999)).
W99-0613
At current state two linguistic resources have been analyzed and adapted in order to be incorporated into the ADVICE project: Brill tagger, Brill (1992), and EuroWordNet, Vossen et al.(1998). The paper is structured as follows: next section focuses on a brief description of the NL module of ADVICE project; section 3 is devoted to explain how the corpus study has influenced the customization of the lexical resources; sections 4 and 5 outline the Brill tagger and EuroWordnet extension to cover specific domain peculiarities and, finally, in section 6 some conclusions and future work are presented.
A92-1021
