Three semantic lexicon learners have previously been evaluated on the MUC-4 corpus (Rilo and Shepherd, 1997; Roark and Charniak, 1998; Rilo and Jones, 1999), and of these meta-bootstrapping achieved the best results.
P98-2182
Even for relatively general texts, such as the Wall Street Journal (Marcus et al., 1993) or terrorism articles (MUC4 Proceedings, 1992), Roark and Charniak (Roark and Charniak, 1998) reported that 3 of every 5 terms generated by their semantic lexicon learner were not present in WordNet.
J93-2004 P98-2182
Hale, Ge, and Charniak (Ge et al., 1998) devised a technique to learn the gender of words.
W98-1119
Several learning algorithms have also been developed for named entity recognition (e.g., (Collins and Singer, 1999; Cucerzan and Yarowsky, 1999)).
W99-0612 W99-0613
Semantic class information has proven to be useful for many natural language processing tasks, including information extraction (Rilo and Schmelzenbach, 1998; Soderland et al., 1995), anaphora resolution (Aone and Bennett, 1996), question answering (Moldovan et al., 1999; Hirschman et al., 1999), and prepositional phrase attachment (Brill and Resnik, 1994).
C94-2195 P99-1042
Caraballo (Caraballo, 1999) and Hearst (Hearst, 1992) created techniques to learn hypernym/hyponym relationships.
C92-2082 P99-1016
Rilo and Shepherd (Rilo and Shepherd, 1997) developed a bootstrapping algorithm that exploits lexical co-occurrence statistics, and Roark and Charniak (Roark and Charniak, 1998) re ned this algorithm to focus more explicitly on certain syntactic structures.
P98-2182
(Collins and Singer, 1999) used contextual information of a di erent sort than we do.
W99-0613
