We further require that each side of the corpus be partof-speech (POS) tagged and phrase chunked; our lab has previously developed techniques for rapid training of such tools (Cucerzan and Yarowsky, 2002).
W02-2006
Wu (1997) and Jones and Havrilla (1998) have sought to more closely tie the allowed motion of constituents between languages to those syntactic transductions supported by the independent rotation of parse tree constituents.
J97-3002
Brown et al., 1993), is grounded in the noisy channel model.
J93-2003
In contrast, Och et al.(1999) have avoided the constraints of tree-based syntactic models and allow the relatively flat motion of empirically derived phrasal chunks, which need not adhere to traditional constituent boundaries.
W99-0604
Bangalore and Riccardi, 2000), which offers the considerable advantage of a flexible framework for decoding, as well as a representation which is suitable for the fixed two-level phrasal modelling employed here.
W00-0508
Yamada and Knight (2000, 2001) and Alshawi et al.(2000) have effectively extended such syntactic transduction models to fully functional SMT systems, based on channel model tree transducers and finite state head transducers respectively.
J00-1004 P01-1067
We used alignments generated by Giza++ (Och and Ney, 2000) by running it in both directions (e.g., Arabic ! English and English ! Arabic) on our parallel corpora.
P00-1056
In each case, results for a comparison system – the Giza++ IBM Model 4 implementation (Och and Ney, 2000) with the ReWrite decoder (Marcu and Germann, 2002) – are included as a benchmark.
P00-1056
POS tagging and phrase chunking in English were done using the trained systems provided with the fnTBL Toolkit (Ngai and Florian, 2001); both were trained from the annotated Penn Treebank corpus (Marcus et al., 1993).
J93-2004 N01-1006
Finally, the original cross-part-of-speech lexical coercion models presented in Section 4.3.3 have related work in the primarily-syntactic coercion models utilized by Dorr and Habash (2002) and Habash and Door (2003), although their induction and modelling are quite different from the approach here.
N03-1013
Wu. 1997.
J97-3002
