NE tagging selects a semantic type for each word so that a sentence can be mapped into a suitable LSP sequence by searching several types in the semantic dictionaries (An et al., 2003).
P03-2031
The performance of the serially connected spoken QA system, based on the QA system from text input which has 76% performance and the output of the ASR which operated at a 30% WER, was only 7% (Harabagiu et al., 2002).
C02-1169
They trained the channel model and the language model both using some transcriptions from TRAINS-95 dialogue system which is a train traveling planning system (Allen et al., 1996).
P96-1009
To measure error correction performance, we use word error rate (WER) and term error rate (TER): WER = jSwj + jIwj + jDwjjW truthj (10) TER = jStj + jItj + jDtjjT truthj (11) jWtruthj is the number of original words, and jTtruthj is the number of query term (or keyword) in original words, that is, an error rate of content words directly related to the performance of IR and QA system (Fujii et al., 2002A).
W02-1025
First, a morphological analysis is performed, which segments a sentence of words into morphemes, and adds POS tags to the morphemes (Lee et al., 2002).
J02-1004
To solve this problem, Ringger and Allen used the fertility of pre-channel word (Ringger and Allen, 1996).
P96-1009
But this improved fertility model only slightly increased the accuracy in experiments (Ringger and Allen, 1996), and we think the major reason is due to the data-sparseness problem.
P96-1009
(Kaki et al., 1998) collected many lexical error patterns that occurred in a speech translation system in Japanese.
P98-1107
Allen. 1996.
P96-1009
(Ringger and Allen, 1996) applied the noisy channel model to the correction of the errors in speech recognition.
P96-1009
So, they introduced a method to improve the precision of speechdriven IR by suggesting a new type of IR system tightlyintegrated with a speech input interface (Fujii et al., 2002B).
W02-1025
Following (Brown et al., 1990), we refer to the number of post-channel words oi produced by a pre-channel word wi as a fertility.
J90-2002
Another group investigated the performance of spoken queries in NTCIR collections (Fujii et al., 2002A).
W02-1025
Another approach has been based on a statistical method utilizing the probabilistic information of words in a spoken dialogue situation and the language models adapted to the application domain (Ringger and Allen, 1996).
P96-1009
(Harabagiu et al., 2002) exposes several fundamental flaws of this simple combination of an automatic speech recognition (ASR) and QA system, including the importance of named entity information, and the inadequacies of current speech recognition technology based on n-gram language models.
C02-1169
Channel Error Correction Model The noisy channel error correction framework has been applied to a wide range of problems, such as spelling correction, statistical machine translation, and ASR error correction (Brill and Moore, 2000; Brown et al., 1990; Ringger and Allen, 1996).
J90-2002 P00-1037 P96-1009
The probability P(W) is given by the language model and can be decomposed as: P(W) = Y i P(wijw1;i¡1) (2) Figure 2: Example of Word-based Channel Model The distribution P(W) can be defined using n-grams, structured language model (Chelba, 1997), or any other tool in the statistical language modeling.
P97-1064
They simplified a statistical machine translation (MT) model called an IBM model (Brown et al., 1990), and tried to construct a general post-processor that can correct errors generated by any speech recognizer.
J90-2002
It has been used in the area of natural language interface for database (NLIDB) (Jung et al., 2003) and a TREC QA system for the purpose of matching the user query with the appropriate answer types at syntax/semantic level (Kim et al., 2001; Lee et al., 2001).
W01-1202
Figure 6 4 shows an example of semantic error correction process using the same data in TRAIN-95 (Allen et al., 1996).
P96-1009
Because Fujii et al.(Fujii et al., 2002B) have shown the importance of the language model which well describes the domain knowledge, we reflect the domain information with a template database: database of template queries of the source statements which are used Figure 5: Process of Semantic-oriented Error Correction for the actual error detection and correction task after speech recognition.
W02-1025
One approach in post error correction, which is a straightforward and intuitive method to robustly handle many kinds of recognition errors, was rule-based approach (Kaki et al., 1998).
P98-1107
1This example is from (Ringger and Allen, 1996).
P96-1009
