The idea of automatically identifying and labeling frame-specific roles, as defined by the semantic frames, was first introduced by (Gildea and Jurasfky, 2002).
J02-3001
Feature Set 1, illustrated in Figure 2 was used in the work reported in (Gildea and Jurasfky, 2002).
J02-3001
The PropBank annotations (www.cis.upenn.edu/ ace) enable training for two distinct learning techniques: (1) decision trees (Surdeanu et al., 2003) and (2) Support Vector Machines (SVMs) (Pradhan et al., 2004).
P03-1002
Additionally, we have performed the following enhancements: we created a multi-class classifier for each frame, thus achieving improved accuracy and efficiency; we combined some new features with features from (Gildea and Jurasfky, 2002; Surdeanu et al., 2003; Pradhan et al., 2004); we resolved the data sparsity problem generated by limited training data for each frame, when using the examples associated with any other frame from FrameNet that had at least one FE shared with each frame that was evaluated; we crafted heuristics that improved mappings from the syntactic constituents to the semantic roles.
J02-3001 P03-1002
The CONTENT WORD (cw) feature illustrated in Figure 3 applies to PPs, SBARs and VPs, as it was reported in (Surdeanu et al., 2003).
P03-1002
These sentences were parsed with the Collins’ parser (Collins, 1997).
P97-1003
The semantic parsing defined as two different classification tasks was introduced in (Gildea and Jurasfky, 2002).
J02-3001
Figure 2: Feature Set 1 (FS1) Feature Set 2 was introduced in (Surdeanu et al., 2003) and it is illustrated in Figure 3.
P03-1002
The evaluation of the Senseval-3 task for Automatic Labeling of Semantic Roles is based on the annotations made available by the FrameNet Project (Baker et al., 1998).
P98-1013
