A detailed description of the notation is presented in Moldovan and Rus (2001).
P01-1052
The derivation of these arguments follows from a slot-filling approach and is based on the interpretation of the parse tree structure and the associated transformation rule (Moldovan and Rus, 2001).
P01-1052
Dan Moldovan et al.2003. COGEX: A Logic Prover for Question Answering.
N03-1022
A Logic Prover (Rus, 2002; Moldovan et al., 2003) utilizing the axioms generated by the Logic Form generation system boosts the performance of the Question Answering system.
N03-1022
Senseval 3 Logic Forms: A System and Possible Improvements Altaf Mohammed, Dan Moldovan, and Paul Parker Language Computer Corporation Richardson, TX 75080 {altaf, moldovan, parker}@languagecomputer.com Abstract Logic Forms, particular powerful logic representations presented in Moldovan and Rus (2001), are simple yet highly effective.
P01-1052
