A quite different approach from our hypotheses testing implemented in the TREQ-AL aligner is taken by the model-estimating aligners, most of them relying on the IBM models (1 to 5) described in the (Brown et al.1993) seminal paper.
J93-2003
The first check was performed by using McNamer’s test (Dieterich, 1998) and for the second we used Brill &Wu test (Brill, Wu, 1998).
P98-1029
19-51 Och, F.J., Ney, H.(2000) "Improved Statistical Alignment Models".
P00-1056
The first one is a hypotheses testing approach (Gale and Church, 1991; Melamed, 2001; Tufiş 2002) while the second one is closer to a model estimating approach (Brown et al., 1993; Och and Ney, 2000).
H91-1026 J93-2003 P00-1056
If none of the alignment clues or their combination (Tiedemann, 2003) is strong enough, the functional words are automatically aligned with the word(s) their governor is aligned to.
E03-1026
GIZA has been superseded by its recent extension GIZA++ (Och and Ney, 2000, 2003) publicly available 2. We used the translation probabilities generated by GIZA++ for implementing a second aligner, MEBA, described in a 1 http://www.cs.unt.edu/~rada/wpt/index.html#shared 2 http://www.fjoch.com/GIZA++.2003-09-30.tar.gz little more details in a subsequent section.
J03-1002 P00-1056
