The most commonly used automatic evaluation metrics, BLEU (Papineni et al., 2002) and NIST (Doddington, 2002), are based on the assumption that The closer a machine translation is to a professional human translation, the better it is (Papineni et al., 2002).
P02-1040
Fox. 2002.
W02-1039
BLEU and NIST have been shown to correlate closely with human judgments in ranking MT systems with different qualities (Papineni et al., 2002; Doddington, 2002).
P02-1040
The translations were generated by the alignment template system of Och (2003).
P03-1021
Dependency trees were found to correspond better across translation pairs than constituent trees by Fox (2002), and form the basis of the machine translation systems of Alshawi et al.(2000) 27 reference: S NP PRON VP V NP ART N hypothesis: S NP PRON VP V NP PRON Figure 2: Examples for the Computation of STM and Lin (2004).
C04-1090 J00-1004 W02-1039
Indeed, in some recent work on re-ranking machine translation hypotheses (Och et al., 2004), parserproduced structures were not found to provide helpful information, as a parser is likely to assign a goodlooking structure to even a lousy input hypothesis.
N04-1021
