Previous research on LVCs, on the other hand, has primarily focused on their automatic extraction (e.g., Grefenstette and Teufel 1995; Dras and Johnson 1996; Moir´on 2004; though see Stevenson et al.2004). Like most previous studies that focus on semantic properties of MWEs, we are interested in the issue of compositionality.
E95-1014 W04-0401
Our ACPT measure yields good correlations with human acceptability judgments; indeed, the average increase over the baseline is about twice as high as that of the acceptability measure proposed by Stevenson et al.(2004). Although ACPT also somewhat reflects different patterns across semantic classes, the results clearly indicate the need for incorporating more knowledge into the measure to capture class-based behaviour more consistently.
W04-0401
To account for resulting errors, we compare the two confidence intervals, a1 ASSOC pos a2 ∆ASSOC pos a3 and a1 A SSOCneg a2 ∆ASSOCneg a3, as in Lin (1999).
P99-1041
such an approach to verb particle constructions by Villavicencio, 2003).
W03-1808
Villavicencio (2003) used class-based knowledge to extend a VPC lexicon, but assumed that an unobserved VPC is not acceptable.
W03-1808
of Acceptability Our acceptability measure is compared to the human judgments gathered by Stevenson et al.(2004). Two expert native speakers of English rated the acceptability of each potential “LV+PN” construction generated by combining give and take with candidate complements from the development and test Levin classes.
W04-0401
Some research has concentrated on the automatic acquisition of semantic knowledge about certain classes of MWEs, such as compound nouns or verb particle constructions (VPCs) (e.g., Lin, 1999; McCarthy et al., 2003; Villavicencio, 2003).
P99-1041 W03-1808 W03-1810
Bannard et al.(2003), on the other hand, look at the separate contribution of the verb and particle, but assume that a binary decision on the compositionality of each is sufficient.
W03-1809
Previous studies determine compositionality by looking at the degree of distributional similarity between an expression and its component words (e.g., McCarthy et al., 2003; Bannard et al., 2003; Baldwin et al., 2003).
W03-1809 W03-1810 W03-1812
Work indicating acceptability of MWEs is largely limited to collocational analysis using PMI-based measures (Lin, 1999; Stevenson et al., 2004).
P99-1041 W04-0401
1PMI is subject to overestimation for low frequency items (Dunning, 1993), thus we require a minimum frequency of occurrence for the expressions under study.
J93-1003
Since in these LVCs the complement is a predicative noun in stem form identical to a verb, we form development and test expressions by combining give or take with verbs from selected semantic classes of Levin (1993), taken from Stevenson et al.(2004). 4.3 Corpora We gather estimates for our COMP measure from the BNC, processed using the Collins parser (Collins, 1999) and TGrep2 (Rohde, 2004).
W04-0401
McCarthy et al.(2003) determine a continuum of compositionality of VPCs, but do not distinguish the contribution of the individual components.
W03-1810
Regarding the latter, Stevenson et al.(2004) found differing overall levels of (human) acceptability for different Levin classes combined with give and take.
W04-0401
