The recent introduction of probabilistic models of wide-coverage unification-based grammars (Malouf and van Noord, 2004; Kaplan et al., 2004; Miyao and Tsujii, 2005) has opened up the novel possibility of increasing parsing speed by guiding the search path using probabilities.
N04-1013 P05-1011
We used the chunk parser developed by Tsuruoka and Tsujii (2005a).
W05-1514
Geman and Johnson (Geman and Johnson, 2002) proposed a dynamic programming algorithm for finding the most probable parse in a packed parse forest generated by unification-based grammars without expanding the forest.
P02-1036
Previous studies (Abney, 1997; Johnson et al., 1999; Riezler et al., 2000; Miyao et al., 2003; Malouf and van Noord, 2004; Kaplan et al., 2004; Miyao and Tsujii, 2005) defined a probabilistic model of unification-based grammars as a log-linear model or maximum entropy model (Berger et al., 1996).
J96-1002 J97-4005 N04-1013 P00-1061 P05-1011 P99-1069
Beam thresholding (Goodman, 1997) is a simple and effective technique for pruning edges during parsing.
W97-0302
This evaluation scheme was the same as used in previous evaluations of lexicalized grammars (Hockenmaier, 2003; Clark and Curran, 2004; Miyao and Tsujii, 2005).
P03-1046 P04-1014 P05-1011
Model parameters λi are estimated using numer104 ical optimization methods (Malouf, 2002) so as to maximize the log-likelihood of the training data.
W02-2018
HPSG parsing with a CFG chunk parser A hybrid of deep parsing and shallow parsing was recently found to improve the efficiency of deep parsing (Daum et al., 2003; Frank et al., 2003; Frank, 2004).
C04-1185 E03-1052 P03-1014
Large constituent inhibition (Kaplan et al., 2004) It is unlikely for a large medial edge to contribute to the final parsing result if it spans more than 20 words and is not adjacent to the beginning or ending of the sentence.
N04-1013
Abney. 1997.
J97-4005
To make the model estimation tractable, Geman and Johnson (Geman and Johnson, 2002) and Miyao and Tsujii (Miyao and Tsujii, 2002) proposed a dynamic programming algorithm for estimating p(T|w).
P02-1036
Probabilistic models where probabilities are assigned to the CFG backbone of the unification-based grammar have been developed (Kasper et al., 1996; Briscoe and Carroll, 1993; Kiefer et al., 2002), and the most probable parse is found by PCFG parsing.
C02-1075 J93-1002
We introduce a CFG chunk parser (Tsuruoka and Tsujii, 2005a) as a preprocessor of HPSG parsing.
W05-1514
of failed sentences development set 88.21% 87.32% 87.76% 360 12 test set 87.85% 86.85% 87.35% 360 15 Figure 7: Parsing time for the sentences in Section 24 of less than 15 words of Viterbi parsing (none) (Left) and iterative parsing (iterative) (Right) Figure 6: Parsing time versus sentence length for the sentences in Section 23 of less than 40 words 5 Evaluation We evaluated the efficiency of the parsing techniques by using the HPSG for English developed by Miyao et al.(2005). The lexicon of the grammar was extracted from Sections 02-21 of the Penn Treebank (Marcus et al., 1994) (39,832 sentences).
P05-1011
Most of them were developed for exhaustive parsing, i.e., producing all parse results that are given by the grammar (Matsumoto et al., 1983; Maxwell and Kaplan, 1993; van Noord, 1997; Kiefer et al., 1999; Malouf et al., 2000; Torisawa et al., 2000; Oepen et al., 2002; Penn and Munteanu, 2003).
C02-1075 J97-3004 P03-1026 P99-1061 W02-2018
We first applied beam thresholding techniques developed for CFG parsing to HPSG parsing, including local thresholding, global thresholding (Goodman, 1997), and iterative parsing (Tsuruoka and Tsujii, 2005b).
W05-1514 W97-0302
With the probabilistic model defined in Section 2, we can also define the Viterbi search for unification-based grammars (Geman and Johnson, 2002).
P02-1036
Yoshimasa Tsuruoka and Jun’ichi Tsujii, 2005b.
W05-1514
Next, we applied parsing techniques developed for deep parsing, including quick check (Malouf et al., 2000), large constituent inhibition (Kaplan et al., 2004) and hybrid parsing with a CFG chunk parser (Daum et al., 2003; Frank et al., 2003; Frank, 2004).
C04-1185 E03-1052 N04-1013 P03-1014
They include grammar compilation (Tomita, 1986; Nederhof, 2000), the Viterbi algorithm, controlling search strategies without FOM such as left-corner parsing (Rosenkrantz and Lewis II, 1970) or headcorner parsing (Kay, 1989; van Noord, 1997), and with FOM such as the beam search, the best-first search or A* search (Chitrao and Grishman, 1990; Caraballo and Charniak, 1998; Collins, 1999; Ratnaparkhi, 1999; Charniak, 2000; Roark, 2001; Klein and Manning, 2003).
A00-2018 J00-1003 J01-2004 J97-3004 J98-2004 N03-1016
The probabilistic disambiguation model of the grammar was trained using the same portion of the treebank (Miyao and Tsujii, 2005).
P05-1011
Global thresholding is also used for pruning edges, and was originally proposed for CFG parsing (Goodman, 1997).
W97-0302
However, previous research (Miyao et al., 2003; Clark and Curran, 2004; Kaplan et al., 2004) showed that predicate-argument relations can be represented under the assumption of feature locality.
N04-1013 P04-1014
Yusuke Miyao, Takashi Ninomiya, and Jun’ichi Tsujii, 2005.
P05-1011
These techniques were evaluated in experiments on the Penn Treebank (Marcus et al., 1994) with the wide-coverage HPSG parser developed by Miyao et al.(Miyao et al., 2005; Miyao and Tsujii, 2005).
P05-1011
beam thresholding We tested the iterative beam thresholding proposed by Tsuruoka and Tsujii (2005b).
W05-1514
