Some of these correspond to aspectual features of events, which have been intensively investigated (e.g., Vendler, 1967; Dowty, 1979; Moens and Steedman, 1988; Passonneau, 1988).
J88-2003 J88-2005
Feature evaluation in (Pan et al., 2006b) shows that most of the performance comes from event word or phrase itself.
P06-1050
Experimental results show that the use of the annotation guidelines resulted in about 10% improvement in inter-annotator agreement, measured as described in this section, see (Pan et al., 2006a) for details.
P06-1050
These are described in detail in (Pan et al., 2006a).
P06-1050
The kappa statistic (Krippendorff, 1980; Carletta, 1996) has become the de facto standard to assess inter-annotator agreement.
J96-2004
For a given event, both the head of its subject and the head of its object are extracted from the parse trees generated by the CONTEX parser (Hermjakob and Mooney, 1997).
P97-1062
Because the annotated corpus is still fairly small, we cannot hope to learn to make finegrained judgments of event durations that are currently annotated in the corpus, but as we show in greater detail in (Pan et al., 2006b), it is possible to learn useful coarse-grained judgments that considerably outperform a baseline and approach human performance.
P06-1050
Passonneau. 1988.
J88-2005
In the literature on the kappa statistic, most authors address only category data; some can handle more general data, such as data in interval scales or ratio scales (Krippendorff, 1980; Carletta, 1996).
J96-2004
Although there has been much work on extracting and inferring such information from texts (Hitzeman et al., 1995; Mani and Wilson, 2000; Filatova and Hovy, 2001; Boguraev and Ando, 2005), none of this work has exploited the implicit event duration information from the text.
E95-1035 P00-1010 W01-1313
To extract such implicit event duration information from texts automatically, we developed a corpus annotated with typical durations of events (Pan et al., 2006a) which currently contains all the 48 non-Wall-Street-Journal (non-WSJ) news articles (a total of 2132 event instances), as well as 10 WSJ articles (156 event instances), from the TimeBank corpus annotated in TimeML (Pustejovky et al., 2003).
P06-1050
(Rieger 1974)’s ORDERHOURS, ORDERDAYS), are shown in (Pan et al., 2006b).
P06-1050
