We followed the approximation described in (Collins et al., 2005) to get around this problem.
P05-1066
A bootstrapping method is used to calculate the 95% confidence intervals for BLEU (Koehn, 2004; Zhang and Vogel, 2004).
W04-3250
We used the N-best list generated by the Hiero SMT system (Chiang, 2005).
P05-1033
work and discussion Yamamoto and Church (2001) used suffix arrays to compute the frequency and location of an ngram in a corpus.
J01-1001
Kirchhoff and Yang (2005) used a factored 3gram model and a 4-gram LM (modified KN smoothing) together with seven system scores to re-rank an SMT N-best.
W05-0821
Statistical language modeling has been widely used in natural language processing applications such as Automatic Speech Recognition (ASR), Statistical Machine Translation (SMT) (Brown et al., 1993) and Information Retrieval (IR) (Ponte and Croft, 1998).
J93-2003
The PMI over the natural cut quantifies the non-compositionality Inc of an n-gram wji . The higher the value of Inc(wji) the more likely wji is a meaningful constituent, in other words, it is less likely that wji is composed from two short n-grams just by chance (Yamamoto and Church, 2001).
J01-1001
The decoder uses different models, such as the translation model, n-gram language model, fertility model, and combines multiple model scores to calculate the objective function value which favors one translation hypothesis over the other (Och et al., 2004).
N04-1021
