In this paper, we evaluate the approach proposed in (Cao and Li, 2002) by introducing a total scoring function 17 that is based on validating translation candidates directly through the search engine.
C02-1011
Suppose that we have sample terms of a specific domain/topic, then the technical terms that are to be listed as the headwords of a bilingual lexicon are collected from the Web by the related term collection method of (Sato and Sasaki, 2003).
P03-2020
In the first approach, translation candidates are validated through the search engine (Cao and Li, 2002).
C02-1011
The scoring function ‘D’ is a variant of the model proposed by (Tonoike et al., 2005) and ‘E’ corresponds to the bilingual lexicon score of the scoring function ‘D’.
I05-2020
In the method of (Cao and Li, 2002), the translation candidates of a term are compositionally generated by concatenating the translation of the constituents of the term and are validated directly through the search engine.
C02-1011
Another technique which seems to be useful is that of transliteration of names (Knight and Graehl, 1998; Oh and Choi, 2005).
I05-2012 J98-4003
The scoring function ‘I’ is intended to evaluate the approach proposed in (Cao and Li, 2002).
C02-1011
T ) translation set (language T ) web (language S ) web (language S ) existing bilingual lexicon X S M (# of translations is more than one) Y S (# of translations is zero) web (language T ) web (language T ) looking up bilingual lexicon validating translation candidates web (language T ) web (language T ) Figure 1: Compilation of a Domain/TopicSpecific Bilingual Lexicon using the Web before translation estimation, then generated translation candidates are validated against the domain/topic-specific corpus (Tonoike et al., 2005).
I05-2020
One of them is that based on collecting partially bilingual texts through the search engine (Nagata and others, 2001; Huang et al., 2005).
H05-1061 W01-1413
For example, in the case of estimation from comparable corpora, (Fung and Yee, 1998; Rapp, 1999) proposed standard techniques of estimating bilingual term correspondences from comparable corpora.
P98-1069 P99-1067
(Cao and Li, 2002) also proposed a method of compositional translation estimation for compounds.
C02-1011
M. Nagata et al.2001. Using the Web as a bilingual dictionary.
W01-1413
