Cunningham, et al.2002. GATE: A Framework and Graphical Development Environment for Robust NLP Tools and Applications.
P02-1022
12 of ENTITY (which will include PHYSICAL ENTITY and ABSTRACT ENTITY).3 4 Experimental Setup 4.1 Corpus and Experimental Expressions We use the British National Corpus (BNC),4 automatically parsed using the Collins parser (Collins, 1999), and further processed with TGrep2.5 We select our potential experimental expressions from pairs of verb and direct object that have a minimum frequency of 25 in the BNC and that involve one of a predefined list of basic (transitive) verbs.
P99-1065
We then describe our port of the Collins (1999) parser to Chinese.
P99-1065
Yarowsky (1995), Collins and Singer (1999), Riloff and Jones (1999)).
P99-1065
7This property turned out to be problematic for adapting the GF Parallel Resource Grammar to Russian (Khegai, 2006).
P06-2062
Probably the best known such a general system is GATE (Cunninghametal.,1995;Cunninghametal.,2002), which contains some NE resources for Bulgarian and Russian (Humphreys et al., 2002; Popov et al., 2004) and allows to write shallow (regular) grammars in the JAPE subsystem (Cunningham et al., 2000).
P02-1022
Dependency trees are created by extracting a headword for each node of the syntactic tree, according to the rules used by the parser of Collins (1999), where every subtree represents the modifier information for its root headword.
P99-1065
M. Collins, J. Hajic, L. Ramshaw, and C. Tillmann. 1999 A Statistical Parser for Czech. In Proceedings of ACL pages 505512.
P99-1065
parser, the Collins (1999) parser, ported to Chinese.
P99-1065
methods that can be bootstrapped from a little seed data or a few seed rules (Collins, 1999; Cucerzan, 1999) are highly demanded to automatically annotate the training data.
P99-1065
In recent years, many accurate phrase-structure parsers have been developed (e.g., (Collins, 1999; Charniak, 2000)).
P99-1065
First, the semantic head of each constituent is identified using head rules similar to those of Collins (1999) and untyped dependencies are then extracted and labeled with the most specific grammatical relations possible using Tregex rules (Levy and Andrew, 2006).
P99-1065
10Following Collins et al. (1999), we used a coarsened ver-
P99-1065
is Hard There are various characteristics of Slavonic languages1 that make them more difficult for automatic processing, whether shallow or deep, than Germanic and Romance languages.2 The two of them which are most conspicuous, and identified as most problematic, e.g., in (Collins et al., 1999), are rich nominal inflection (2.1) and free word order (2.6).
P99-1065
Moreover,forBulgarianamoregeneralintegrated system was developed, called LINGUA (Tanev and Mitkov, 2002), which ??apart from modules for 12Again, this test may fail due to case syncretisms; cf.
C02-1027
Collins parser for Chinese The Collins parser is a state-of-the-art statistical parser that has high performance on English (Collins, 1999) and Czech(Collins et al.1999). There have been attempts in applying other algorithms in Chinese parsing (Bikel and Chiang, 2000; Chiang and Bikel 2002; Levy and Manning 2003), but there has been no report on applying the Collins parser on Chinese.
P99-1065
The language for specification of segments is based on the query syntax of the Poliqarp corpus search engine (Przepirkowski et al., 2004; Janus and Przepirkowski, 2007), in turn based on CQP (Christ, 1994).
P07-2022
Collins. 1999.
P99-1065
Michael Collins. 1999. Head-Driven Statistical Models for Natural Language Parsing. Ph.D. thesis, University of Pennsylvania.
P99-1065
Many of these features required creating an automatic parse; in doing so we showed that the Collins (1999) parser when ported to Chinese achieved the best reported performance on Chinese syntactic parsing.
P99-1065
One example is (Sharoff, 2004), where shallow parsing is used for the identification of prepositional Multi Word Expressions in Russian, with the following explanation of reasons for performing some language-dependent processing: ?Given that the word order in Russian (and other Slavonic languages) is relatively free and a typical word (i.e.
W04-0403
Here, as in GATE (Cunningham, 2002), processing resource refers to programmatic or algorithmic resources, while language resource refers to data-only static resources such as lexicons or corpora.
P02-1022
generated by the parsers of Collins (1999) and Char-
P99-1065
For each of these BIBC expressions, BDBCBC sentences containing its usage were randomly selected from the automatically parsed BNC (Collins, 1999), using the automatic VNC identification method described by FS06.
P99-1065
In our experiments, we have applied the COLLINS (Collins, 1999) parser to generate the syntactic tree of both pieces of text.
P99-1065
We use 20,000 sentences randomly selected from the British National Corpus (BNC),4 automatically parsed using the Collins parser (Collins, 1999), and further processed with TGrep2,5 and an NP-head extraction software.6 For 2To our knowledge, the only work that considers selectional preferences of subjects and prepositional phrases as well as direct objects is Brockmann and Lapata (2003).
P99-1065
