Generation The texts used for these experiments were parsed using the Stanford dependency parser (Klein and Manning, 2002).
W02-1111
Our system uses the typed dependency tree generated by the Stanford Parser (Klein & Manning, 2002).
W02-1111
Manning and Schtze (1999) or Bod (2002).
W02-1111
Inthispaper, wepresentanewtextsemanticsimilarityapproachforfine-grainedpersonnamecategorization and discrimination which is similar to those of (Pedersen et al., 2005) and (Bagga and Baldwin, 1998), but instead of simple word co-occurrences, we consider the whole text segment and relate the deduced semantic information of Latent Semantic Analysis (LSA) to trace the text cohesion between thousands of sentences containing named entities which belong to different fine-grained categories or individuals.
P98-1012
Manning. 2002.
W02-1111 W02-1111
Similar approachwas developedby (Bagga andBaldwin, 1998), who created first order context vectors that represent the instance in which the ambiguous name occurs.
P98-1012
(Tanev and Magnini, 2006) classified geographic location and person names into several subclasses.
E06-1003
(Mann, 2002) populated a fine-grained proper nounontologyusingcommonnounpatternsand following the hierarchy of WordNet.
W02-1111
For fine-grainedpersonNE categorization, (Fleischman and Hovy, 2002) carried out a supervised learning for which they deduced features from the local context in which the entity resides, as well as semantic information derived from the topic signatures and WordNet.
C02-1130
