First, we assume that all the positive training in1For direct comparability with our earlier research, semantic relations used in our examples are taken from (Barker and Szpakowicz, 1998), and differ slightly from those used in the SemEval-2007 task.
P98-1015
Nastase and Szpakowicz (2003) present a two-level hierarchy for classifying noun-modifier relations in base noun phrases from general text, with 5 classes at the top and 30 classes at the bottom; other researchers (Turney and Littman, 2005; Turney, 2005; Nastase et al., 2006) have used their class scheme and data set.
P06-1040
This approach has been applied to problems like compound noun interpretation (Rosario and Hearst 2001) and semantic role labeling (Gildea and Jurafsky 2002).
P02-1032
Turney. 2006.
P06-1040
Rosario et al.(2002) classify noun compounds using the MeSH hierarchy and a multi-level hierarchy of semantic relations, with 15 classes at the top level.
P02-1032
Barker and Szpakowicz (1998) propose a two-level hierarchy with 5 classes at the upper level and 30 at the lower level.
P98-1015
Kim and Hovy (2006) integrated verb information from FrameNet and incorporated it into semantic role labeling.
P06-2064
Turney (2006) discusses word similarity (which he calls ?attributional similarity?? and relation similarity, but focusses on the latter and does not perform a comparative study of the kind presented here.
P06-1040
Rosario et al.(2002) use a ?descent of hierarchy?? which characterizestherelationbasedonthesemanticcategoryof the two nouns.
P02-1032
of the previous studies (Kim et al., 2004; Okanohara et al., 2006; Tzong-Han Tsai et al., 2006), features of shallow parsers had a large contribution to the performance.
P06-2064
Following Turney and Littman (2005) and Barker and Szpakowicz (1998), we used a 1-nearestneighbor classifier.
P98-1015
Turney (2006) induces patterns from the Web, e.g.
P06-1040
The same argument applies to the automatic assessment of product review usefulness (Kim et al., 2006c): 125 Stars Label on the website Number star Poor Post 1251 starstar Below Average Post 44 starstarstar Average Post 69 starstarstarstar Above Average Post 183 starstarstarstarstar Excellent Post 421 Table 1: Categories and their usage frequency.
P06-2064
CAUSE is best characterized by ?Y * causes X?? and ?Y in * early X?isthebestpatternforTEMPORAL.KimandBaldwin (2006) propose to use a predefined set of seed verbs and multiple resources: WordNet, CoreLex, and Moby?s thesaurus.
P06-2064
Turney (2006) presents a more flexible framework in which automatically identified n-gram features replace fixed unigrams and additional word pairs are generated by considering synonyms, but this method still requires a Web-magnitude corpus and a very large amount of computational time and storage space.
P06-1040
Kim et al.(2006b) found that the relation between a student?s posting behavior and the grade obtained by that student can be assessed automatically.
P06-2064
1Such as Girju et al.(2005), Girju (2006), Turney (2006).
P06-1040
objective ??have attracted considerable attention in the recent years (Hu and Liu, 2004; Kim and Hovy, 2005; Riloff et al., 2006; Turney and Littman, 2003; Yu and Hatzivassiloglou, 2003).
P06-2064
The proposed task is a generalisation of the more conventional task of interpreting noun compounds (NCs), inwhichwetakeaNCsuchas cookie jar and interpret it according to a pre-dened inventory of semantic relations (Levi, 1979; Vanderwende, 1994; BarkerandSzpakowicz, 1998).
P98-1015
(Kim and Baldwin, 2006) use a set of seed verbs to characterize the semantic relation between the constituent nouns and explores a parsed corpus to classify NCs.
P06-2064
Feng et al.(2006) and Kim et al.(2006a) describe a system to find the most authoritative answer in a forum thread.
P06-2064
Kimo Blog from January to July, 2006, spanning a period of 212 days.
P06-2064
