Lauri Karttunen. 1994. Constructing lexical transduc-
C94-1066
Ronald M. Kaplan and Martin Kay. 1994. Regular 
J94-3001
Kaplan and Kay (1994) developed a method 
J94-3001
Evans et al., 1996), (Black et.al., 1987), (Ruess-
E87-1003
sition (Karttunen, 1994).  Avoiding the separate 
C94-1066
Graeme Ritchie. 1992. Languages generated by two-
J92-1003
ink, 1989), (Ritchie, 1992), (Kiraz, 2001) and a 
J92-1003
