Philipp Koehn and Hieu Hoang. 2007. Factored
D07-1091 P07-2045
Franz Josef Och and Hermann Ney. 2000. Improved
P00-1056
al., 2003) and (Och and Ney, 2004). PB-SMT
J04-4002
Franz Josef Och and Hermann Ney. 2004. The
J04-4002
K. Papineni, S. Roukos, T. Ward, and W. J. Zhu. 2002.
P02-1040
generated by GIZA++21 (Och and Ney, 2000) or the
P00-1056
as Moses (Koehn et al., 2007)10) to train, test
D07-1091 P07-2045
FrameNet18 (Baker et al., 1998), here we propose
P98-1013
(Koehn and Hoang, 2007) and (Tinsley and Way,
D07-1091 P07-2045
researchers from IBM (Brown et al., 1990). In those
J90-2002
