A. Ratnaparkhi, 1996.
W96-0213
J. Goodman, 1996.
W96-0214
The Data-Oriented Parsing (DOP) method suggested in Scha (1990) and developed in Bod (19921995) is a probabilistic parsing strategy which does not single out a narrowly predefined set of structures as the statistically significant ones.
C92-3126
Schabes et al., 1993; Weischedel et al., 1993; Briscoe, 1994; Magerman, 1995; Collins, 1996).
E93-1040 J93-2006 P95-1037 P96-1025
To select the most probable parse from a forest, Bod (1993-95) and Rajman (1995a,b) give Monte Carlo approximation algorithms.
E93-1006
In previous work, we tested the DOP method on a cleaned-up set of analyzed part-of-speech strings from the Penn Treebank (Marcus et al., 1993), achieving excellent test results (Bod, 1993a, b).
E93-1006 J93-2004
Bod (1992, 1993a) shows that conventional context-free parsing techniques can be used in creating a parse forest for a sentence in DOP1.
C92-3126 E93-1006
R. Bod, 1993a.
E93-1006
These have been extensively described in Bod (1993-1995) and Rajman (1995a,b).
E93-1006
To deal with this question, we use ATIS p-o-s trees as found in the Penn Treebank (Marcus et al., 1993).
J93-2004
D. Magerman, 1995.
P95-1037
Church, 1988.
A88-1019
R. Bod, 1992.
C92-3126
As future research, we will apply the full DOP model on WSJ word strings in order to compare our results with the best known parsers on this domain (Magerman, 1995; Collins, 1996).
P95-1037 P96-1025
In Goodman (1996), an efficient parsing strategy is given that maximizes the expected number of correct constituents.
W96-0214
The system developed by (Pereira & Schabes 1992), where use is made of an iterative reestimation algorithm derived from the well-known inside-outside algorithm (Baker, 1979), obtains 90.4% bracketing accuracy.
P92-1017
R. Bod, 1993b.
E93-1006
Sima'an (1996) and Goodman (1996) also report experiments on unedited ATIS trees, their results do not refer to the most probable parse but to the most probable derivation and the maximum constituents parse respectively.
W96-0214
Ratnaparkhi, 1996), a single inconsistency in a test set tree will very likely yield a zero percent parse accuracy for the particular test set sentence.
W96-0213
DOP1 model, and some variations of it, have been tested by Bod (1993-1995), Sima'an (1995-1996), Sekine & Grishman (1995), Goodman (1996), and Charniak (1996).
E93-1006 W96-0214
In Bod (1992, 1993a), a first instantiation of this model is given, called DOP1, which uses (1) labelled trees for the utterance analyses, (2) subtrees for the fragments, (3) nodesubstitution for combining subtrees, and (4), the sum of the probabilities of all distinct ways of generating an analysis as a def'mition of the probability of that analysis.
C92-3126 E93-1006
M. Collins, 1996.
P96-1025
1 Goodman's approach is different from Bod (1993-1995) and Sima'an (1995) in that it returns best parses that cannot be generated by the DOP1 model (see Bod, 1996 for a reply to Goodman's paper).
E93-1006
