Relationship to Past Work While there have been previous investigations of empirical approaches to coreference, these have generally centered on the task of assigning correct referents for anaphor/c expressions (Connolly, Burger, and Day, 1994; Aone and Bennett, 1995; Lappin and Leass, 1994; Dagan 2Templates A, B, C, and D constitute the only coreference set in this example, since none of the other NPs (e.g., the various "areas" mentioned) are compatible with any of the others.
J94-4002 P95-1017
For this we employ an approach to maximum entropy modeling described by Berger et al.(1996). Maximum Entropy Modeling Suppose we wish to model some random process, such as that which determines coreference between two templates generated by an IE system, based on various characteristics of the context that influence this process, such as the content of the templates themselves, the form of the natural language expressions from which the templates were created, and the distance between 165 those expressions in the text.
J96-1002
Berger et al.(1996) show that this model is a member of an exponential family with one parameter for each constraint, specifically a model of the form 1 ~ I~ (x,~) p(yl ) = E' in which z(x) = eZ, Y The parameters A1, ..., An are Lagrange multipliers that impose the constraints corresponding to the chosen features fl, ..-,fnThe term Z(x) normalizes the probabilities by summing over all possible outcomes y.
J96-1002
164 and Itai, 1990; Dagan et al., 1995; Kennedy and Boguraev, 1996a; Kennedy and Boguraev, 1996b).
C96-1021
Berger et al.(1996) demonstrate that the optimal values for the Ai's can be obtained by maximizing the likelihood of the training data with respect to the model, which can be performed using their improved iterative scaling algorithm.
J96-1002
