For the syntactic generator, the relevant syntactic information is extracted in the form of a Feature-Based Lexicalized TAG (FB-LTAG) grammar, see \[Joshi 1987, Vijay-Shanker and Joshi 1991, Schabes, Abeill4, and Joshi 1988\].
C88-2121
For this preprocessing of the HPSG grammar, we adapted the 'HPSG to TAG compilation' process described in \[Kasper et al.1995\]. The basis for the compilation is an identification of syntactically relevant selector features which express subcategorization requirements of a lexical item, e.g. the VALENCE features.
P95-1013
\[Krieger and Sch~fer 1994\] Krieger, Hans-Ulrich and Ulrich Sch~ifer.
C94-2144
The input for the generation module VM-GECO 1 is generated by a semantic-based transfer component (see \[Dorna and Emele 1996\]).
C96-1054
\[Shieber et al.1990\] Shieber, Stuart, Gertjan Van Noord, Fernando Pereira, and Robert Moore.
J90-1004
\[Schabes, Abeill4, and Joshi 1988\] Schabes, Y., A.
C88-2121
\[Dorna and Emele 1996\] Dorna, M.
C96-1054
Development is carried out on a grammar development platform which is based on TDL \[Krieger and Sch£fer 1994\].
C94-2144
' \[Doran and Stone 1997\] Doran, Christy and Matthew Stone.
P97-1026
Work on generation with TAG generally assumes that there is a one, to~-one mapping between the information in the generator input and the choice of elementary tree \[Mcdonald and Pustejovsky 1985, Yang, McCoy, and Vijay-Shanker 1991, D0ran and Stone 1997\].
P97-1026
This separation allows for an easy adaptation of the system to other languages and domains (see \[Becker et al.1998\]). 3 Declarativity in the Syntactic Generator All modules of the generator utilize external, declarative knowledge bases.
P98-1017
It is important to compare the generation strategy presented here with Semantic-head-driven generation \[Shieber et al.1990, van Noord 1990\] which is a direct generation algorithm froni logical form encodings.
J90-1004
\[Kasper et al.1995\] Kasper, R., B.
P95-1013
