As reported in (Argamon et al., 1998), most base NPs present in ~he data are less or equal than 4 words long.
P98-1010
Raw sentences are supplied as input and are processed using a SNoW based POS tagger (Roth and Ze!enko, 1998) first.
P98-2186
These problems formulations are similar to those studied in (Ramshaw and Marcus, 1995) and (Church, 1988; Argamon et al., 1998), respectively.
A88-1019 P98-1010 W95-0107
Perhaps this was not observed earlier since (Ramshaw and Marcus, 1995) studied only base NPs, most of which are short.
W95-0107
This paper presents a general learning approach for identifying syntactic patterns, based on the SNoW learning architecture (Roth, 1998; Roth, 1999).
P98-2186
The data sets include POS tag information generated by Ramshaw and Marcus using Brill's transformational part-of-speech tagger (Brill, 1995).
J95-4004 W95-0107
SV phrases, following the definition suggested in (Argamon et al., 1998), are word phrases starting with the subject of the sentence and ending with the first verb, excluding modal verbs 2.
P98-1010
This approach has been studied in (Ramshaw and Marcus, 1995).
W95-0107
This approach has been studied in (Church, 1988; Argamon et al., 1998).
A88-1019 P98-1010
4.1 Data In order to be able to compare our results with the results obtained by other researchers, we worked with the same data sets already used by (Ramshaw and Marcus, 1995; Argamon et al., 1998) for NP and SV detection.
P98-1010 W95-0107
Church. 1988.
A88-1019
The results are comparable to other results reported using the Inside/Outside method (Ramshaw and Marcus, 1995) (see Table 7.
W95-0107
The observation that shallow syntactic information can be extracted using local information by examining the pattern itself, its nearby context and the local part-of-speech information has motivated the use of learning methods to recognize these patterns (Church, 1988; Ramshaw and Marcus, 1995; Argamon et al., 1998; Cardie and Pierce, 1998).
A88-1019 P98-1010 P98-1034 W95-0107
Of the several slightly different definitions of a base NP in the literature we use for the purposes of this work the definition presented in (Ramshaw and Marcus, 1995) and used also by (Argamon et al., 1998)and others.
P98-1010 W95-0107
Preliminary versions of it have already been used successfully on several tasks in natural language processing (Roth, 1998; Golding and Roth, 1999; Roth and Zelenko, 1998).
P98-2186
This is similar to results in the literature (Ramshaw and Marcus, 1995).
W95-0107
These data sets were based on the Wall Street Journal corpus in the Penn Treebank (Marcus et al., 1993).
J93-2004
